.github/workflows/ci.yml
brakedown/Cargo.toml
brakedown/benches/encode.rs
brakedown/benches/field_batch.rs

And fix the targets that were broken.

Check all targets in CI/CD

---

air/src/virtual_column.rs
brakedown/benches/encode.rs
field/src/field.rs
field/src/packed.rs
goldilocks/src/lib.rs
matrix/src/dense.rs
matrix/src/sparse.rs
merkle-tree/src/lib.rs
mersenne-31/src/complex.rs
mersenne-31/src/lib.rs
util/src/lib.rs

Via
```
cargo +nightly clippy --all-targets --fix -- -D clippy::pedantic
cargo fmt
```

Ask clippy for fixes

---

air/src/air.rs
brakedown/benches/encode.rs
field/src/batch_inverse.rs
field/src/field.rs
field/src/packed.rs
fri/src/prover.rs
goldilocks/src/lib.rs
matrix/src/mul.rs
matrix/src/sparse.rs
merkle-tree/src/lib.rs
mersenne-31/src/lib.rs
multi-stark/src/prover.rs
poseidon/src/lib.rs
tensor-pcs/src/lib.rs
uni-stark/src/prover.rs
uni-stark/tests/mul_air.rs
util/src/lib.rs

Lots of little fixes suggested by clippy::pedantic.

Make clippy happier

---

challenger/Cargo.toml
challenger/src/duplex_challenger.rs

Adds some unit test coverage for `DuplexChallenger` functionality. Mostly, for my own pedagogical understanding.

test: adds coverage for duplex challenger functionality

---

goldilocks/Cargo.toml
goldilocks/benches/goldilocks_inverse.rs
goldilocks/src/lib.rs

This PR adds method to compute inverse of a field element in Goldilocks in constant time.

Goldilocks inverse

---

mersenne-31/src/complex.rs

Included in and necessary for the polynomial/fft pull request

Complex inverse and sampling

---

Cargo.toml
dft/Cargo.toml
dft/benches/fft.rs
dft/src/lib.rs
dft/src/naive.rs
dft/src/radix_2_bowers.rs
dft/src/radix_2_dit.rs
dft/src/traits.rs
dft/src/util.rs
field/Cargo.toml
field/src/field.rs
matrix/src/dense.rs

- naive
- radix 2 DIT
- radix 2 Bowers G^T (h/t @0x0ece)
Coming soon:
- four-step
- packing trick (useful for Mersenne31)
- parallelized versions

A few DFT algorithms

---

challenger/src/duplex_challenger.rs
challenger/src/hash_challenger.rs
challenger/src/lib.rs
commit/src/adapters/multi_from_uni_pcs.rs
commit/src/adapters/uni_from_multi_pcs.rs
commit/src/pcs.rs
fri/src/config.rs
fri/src/lib.rs
fri/src/proof.rs
fri/src/prover.rs
fri/src/verifier.rs
ldt/src/lib.rs
merkle-tree/src/lib.rs
multi-stark/src/config.rs
multi-stark/src/prover.rs
tensor-pcs/src/tensor_pcs.rs
uni-stark/src/config.rs
uni-stark/src/prover.rs
uni-stark/tests/mul_air.rs

With sub-traits for different supported types

Make `Challenger` more flexible

---

dft/src/radix_2_bowers.rs

Seems to give a 2~6% improvement depending on size.
Inspired by @0x0ece's https://github.com/mir-protocol/plonky2/pull/736

Special case Bowers blocks with twiddle factor 1

---

dft/src/radix_2_dit.rs
mds/src/coset_mds.rs

A bit faster, and closer to the Bowers impl

Precompute twiddles upfront

---

.gitignore
symmetric/src/compression.rs
symmetric/src/hasher.rs
uni-stark/Cargo.toml
uni-stark/tests/mul_air.rs

Lets us use Keccak etc to hash field elements.

SerializingHasher32

---

field/src/extension/cubic.rs
field/src/extension/mod.rs
field/src/extension/quadratic.rs
field/src/field.rs
mersenne-31/src/extension.rs

This PR encapsulates X proposed improvements to #75:
1. Remove the redundant OEF trait
2. Fix a spelling mistake
3. Remove the intermediate `scalar_mul` function
4. Remove generic implementation of "scalar multiplication" and provide specialisations

Mersenne31 quadratic extension field improvements

---

Cargo.toml
blake3/Cargo.toml
blake3/src/lib.rs
uni-stark/Cargo.toml
uni-stark/src/prover.rs
uni-stark/tests/mul_air.rs

The standard version, not ideal for hashing small leaves

Add blake3

---

Cargo.toml
poseidon2/Cargo.toml
poseidon2/benches/poseidon2.rs
poseidon2/src/babybear.rs
poseidon2/src/diffusion.rs
poseidon2/src/goldilocks.rs
poseidon2/src/lib.rs

Implements the Posedion2 hash function.

feat: poseidon2

---

poseidon2/src/diffusion.rs
poseidon2/src/lib.rs

Poseidon2 tweaks

---

mersenne-31/src/aarch64_neon.rs

This is basically done; it just needs some cleanup, so there's less code duplication with Baby Bear.

WIP: NEONize M31

---

commit/src/pcs.rs
field/src/field.rs
fri/src/fold_even_odd.rs
ldt/src/ldt_based_pcs.rs
uni-stark/Cargo.toml
uni-stark/src/decompose.rs
uni-stark/src/folder.rs
uni-stark/src/prover.rs
uni-stark/src/verifier.rs
uni-stark/src/zerofier_coset.rs

Mostly finish STARK verifier

---

code/Cargo.toml
code/src/identity.rs
code/src/registry.rs

Adds test coverage to the logic in `identity.rs` and `registry.rs`.

test: adds tests to code crate

---

baby-bear/benches/extension.rs
baby-bear/src/extension.rs
field/src/extension/mod.rs
goldilocks/benches/extension.rs
goldilocks/src/extension.rs
keccak-air/examples/prove_baby_bear_keccak.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_goldilocks_keccak.rs
mersenne-31/benches/extension.rs
mersenne-31/src/extension.rs
uni-stark/tests/mul_air.rs

Re-export to main extension crate to simplify paths

Make binomial_extension private

---

interpolation/src/lib.rs

The `.map(EF::from_base)` call was simplifying things, but leading to unnecessary EF-EF multiplication rather than scalar multiplication.

Preserve base field types during interpolation

---

field/Cargo.toml
keccak-air/Cargo.toml
ldt/Cargo.toml
multi-stark/Cargo.toml
tensor-pcs/Cargo.toml
uni-stark/Cargo.toml

Found via
```bash
cargo udeps --workspace --all-targets --all-features
```

Remove unused dependencies

---

code/src/systematic.rs
dft/src/traits.rs
mersenne-31/src/lib.rs
mersenne-31/src/radix_2_dit.rs

[res] addresses unchecked arithmetic overflow / underflow

---

uni-stark/src/verifier.rs

Address that TODO in the verifier (I think, I assume this was the intention)

Validate the proof shape in uni-stark

---

uni-stark/src/check_constraints.rs
uni-stark/src/lib.rs
uni-stark/src/prover.rs

Makes for easier debugging. Inspired by Valida which has a similar feature.

Check that the trace satisfies each constraint

---

dft/benches/fft.rs
dft/src/radix_2_dit.rs
fri/src/fold_even_odd.rs
fri/tests/fri.rs
ldt/src/quotient.rs
uni-stark/src/decompose.rs

In `Radix2Dit` for now; if we're happy with this style we can do it for others.

Lazily compute twiddles

---

challenger/Cargo.toml
challenger/src/grinding_challenger.rs
challenger/src/lib.rs
fri/src/config.rs
fri/tests/fri.rs
keccak-air/examples/prove_baby_bear_keccak.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_goldilocks_keccak.rs
rescue/src/sbox.rs
symmetric/src/permutation.rs
uni-stark/tests/mul_air.rs

- Make proof-of-work bits configurable
- Parallelize search for the proof-of-work witness

A couple FRI PoW improvements

---

air/src/air.rs

The introduction of `assert_zero_ext` prescribes a specific choice of how to interpret constraints living in an extension field, namely, decomposition of each basis element to a different constraint. This choice creates problems when a different treatment is preferable, e.g. in the case of constraint folders where the accumulator already lives in the extension. 
This PR moves the `assert_zero_ext`, `assert_eq_ext`, and `assert_one_ext` methods from `AirBuilder` to `PermuationBuilder` and also limits their scope to only include expressions of the form `AB::ExprEF`.

refactor: move `assert_zero_ext` to `PermutationBuilder`

---

uni-stark/Cargo.toml

uni-stark needs serde's alloc feature

---

tensor-pcs/Cargo.toml

`$ cd tensor-pcs && cargo build` would fail due to missing serde imports.

[resolve] tensor-pcs did not successfully build

---

field/src/extension/binomial_extension.rs
field/src/field.rs
keccak-air/examples/prove_baby_bear_keccak.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_goldilocks_keccak.rs
uni-stark/src/config.rs
uni-stark/src/folder.rs
uni-stark/src/prover.rs
uni-stark/tests/mul_air.rs

Adds
```rust
pub trait ExtensionField<Base: Field>: Field + AbstractExtensionField<Base> {
type ExtensionPacking: AbstractExtensionField<Base::Packing, F = Self>;
// ...
}
```
to eliminate need for PackedChallenge

Extension packing

---

baby-bear/Cargo.toml
baby-bear/src/baby_bear.rs

@dlubarov I think this might be all that's needed? It took me way longer than it should have, I think I was over-complicating it. But let me know if I missed something!

Baby bear encoding

---

baby-bear/src/x86_64_avx2.rs
mersenne-31/src/aarch64_neon.rs
mersenne-31/src/x86_64_avx2.rs

Clippy gets slightly unhappy when compiled with AVX targeted. No meaningful changes here but should stop clippy complaining.

Make Clippy Happy

---

baby-bear/src/x86_64_avx2.rs
mersenne-31/src/x86_64_avx2.rs

Need to make some small updates to AVX code so it compiles on AVX again.

Currently errors on AVX compile

---

baby-bear/src/baby_bear.rs
brakedown/src/brakedown_code.rs
challenger/src/duplex_challenger.rs
challenger/src/serializing_challenger.rs
field-testing/src/lib.rs
fri/src/fold_even_odd.rs
mersenne-31/src/dft.rs
util/src/array_serialization.rs

Quick followup of #264 + unused import warnings

Rejection sampling for SerializingChallenger64

---

keccak-air/examples/prove_goldilocks_poseidon.rs

There seems to be a minor issue with prove_goldilocks_poseidon.rs.
As far as I can tell this should fix it.

Fix Prove_Goldilocks_Poseidon

---

monolith/benches/permute.rs
monolith/src/monolith.rs

Monolith bench for width 12 as well as 16

---

baby-bear/src/x86_64_avx2.rs
mersenne-31/Cargo.toml
mersenne-31/src/lib.rs
mersenne-31/src/mersenne_31.rs
mersenne-31/src/x86_64_avx2.rs
mersenne-31/src/x86_64_avx512.rs

I've put it under a `nightly-features` flag since AVX-512 is _still_ unstable.

AVX-512 implementation of Mersenne-31 arithmetic

---

baby-bear/src/mds.rs
mds/src/karatsuba_convolution.rs
mds/src/util.rs
uni-stark/src/symbolic_builder.rs

Corrected debug output on `uni-stark/src/symbolic_builder.rs` and minor typos on comments

Corrected debug output

---

README.md
baby-bear/Cargo.toml
baby-bear/src/baby_bear.rs
baby-bear/src/lib.rs
baby-bear/src/x86_64_avx2.rs
baby-bear/src/x86_64_avx512.rs

It's mostly the same code as the AVX2 implementation… The richer instruction set lets shave a few instructions from multiplication though.

BabyBear AVX-512

---

uni-stark/src/prover.rs

- Modified the mutability of `sels` variable in `prover.rs`.
- Implemented padding for default values in cases of smaller `quotient_size`.
- Updated calculation logic to account for smaller `quotient_size` in the "Transpose" step.
Motivation: #275 introduced a `PackedVal<SC>::WIDTH` as high as 16.

refactor: Refactor quotient_values for better handling of small quotient size

---

keccak-air/examples/prove_baby_bear_keccak.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_goldilocks_keccak.rs
keccak-air/examples/prove_goldilocks_poseidon.rs
keccak-air/examples/prove_m31_keccak.rs

680 seems a bit too fast now after all the speedups.

Increase the number of hashes in keccak-air benchmarks

---

mersenne-31/src/aarch64_neon/poseidon2.rs

This PR fixes the bug in the tests mentioned here #341 
Feel free to accept or reject as I know the change is small and might be fixed elsewhere. 
Closes #341

This PR Fixes a bug in the tests

---

baby-bear/benches/bench_field.rs
mersenne-31/benches/bench_field.rs

close:https://github.com/Plonky3/Plonky3/issues/343

chore:fix all typos

---

fri/src/two_adic_pcs.rs

Fix parens in comment

---

mersenne-31/src/x86_64_avx512/poseidon2.rs

Fix M31 AVX512 Poseidon test duplication

---

field/src/field.rs

Fix `from_base_slice` comment

---

baby-bear/src/aarch64_neon/packing.rs
koala-bear/src/aarch64_neon/packing.rs
monty-31/src/aarch64_neon/mod.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/aarch64_neon/poseidon2.rs
monty-31/src/data_traits.rs
monty-31/src/monty_31.rs

Adapting the Neon code to work with the monty-31 field type.
Should be getting close to merging this into main.
Need to check this compiles on Neon before we can merge.

Neon baby-koala refactor

---

baby-bear/src/aarch64_neon/packing.rs
baby-bear/src/baby_bear.rs
baby-bear/src/poseidon2.rs
baby-bear/src/x86_64_avx2/packing.rs
baby-bear/src/x86_64_avx512/packing.rs
koala-bear/src/aarch64_neon/packing.rs
koala-bear/src/koala_bear.rs
koala-bear/src/poseidon2.rs
koala-bear/src/x86_64_avx2/packing.rs
koala-bear/src/x86_64_avx512/packing.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/data_traits.rs
monty-31/src/extension.rs
monty-31/src/lib.rs
monty-31/src/mds.rs
monty-31/src/monty_31.rs
monty-31/src/poseidon2.rs
monty-31/src/utils.rs
monty-31/src/x86_64_avx2/packing.rs
monty-31/src/x86_64_avx512/packing.rs

Reworking how traits work in the babybear-koalabear code refactor.
Still not merging anything into main but definitely getting closer.
I know that this doesn't compile currently, I haven't updated the BabyBear/Koalabear crates with the changes here.

Baby koala refactor fieldtraits

---

keccak-air/src/air.rs
keccak-air/src/columns.rs
keccak-air/src/generation.rs

Cherry pick this fix (https://github.com/Plonky3/Plonky3/pull/355) into the sp1-v2 branch.

fix: cherry pick keccak air fix into sp1 branch

---

keccak-air/src/air.rs

* added bool checks in keccak air
* formatting fixes

fix: cherry pick keccak air bool check fix into sp1-v2 branch

---

dft/Cargo.toml
dft/src/radix_2_dit_parallel.rs

Should remove an index out of bound check. (Unless the compiler has already found a way around it)

Remove an index_out_of_bound_check.

---

Cargo.toml
poseidon2-air/Cargo.toml
poseidon2-air/examples/prove_poseidon2_koala_bear_keccak.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_poseidon2.rs
poseidon2-air/src/air.rs
poseidon2-air/src/columns.rs
poseidon2-air/src/generation.rs
poseidon2-air/src/lib.rs

With support for S-boxes of higher degree than our constraint system; based on @bhgomes's https://github.com/valida-xyz/valida/pull/10

Poseidon2 AIR

---

field/src/extension/binomial_extension.rs
uni-stark/src/folder.rs
uni-stark/src/prover.rs

from_base_fn

---

uni-stark/src/folder.rs
uni-stark/src/prover.rs

After this precomputation, the per-row constraint folding work becomes `base * extension` math, rather than `extension * extension`.

Precompute powers of alpha to speed up constraint folding

---

fri/src/two_adic_pcs.rs
matrix/src/lib.rs

- More timing
- Use zero_vec
- Style change

Trivial tweaks

---

field/src/extension/complex.rs
mersenne-31/src/complex.rs
mersenne-31/src/extension.rs
monty-31/src/extension.rs
monty-31/src/monty_31.rs

More explicit inlining

---

air/src/air.rs

Close https://github.com/Plonky3/Plonky3/issues/466

feat: Add AirWithPublicValues

---

fri/src/two_adic_pcs.rs
uni-stark/tests/fib_air.rs

Closes https://github.com/Plonky3/Plonky3/issues/414
Would appreciate if @rjeli could check if this reasoning looks okay.

fix: `TwoAdicFriPcs` verify debug assert for trace height 1

---

goldilocks/src/x86_64_avx512/packing.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/x86_64_avx512/packing.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/x86_64_avx512/packing.rs

Just cleaning up an error I made in the previous PR renaming `AbstractField` -> `FieldAlgebra`

Minor Fmt Fix

---

matrix/src/lib.rs

Improve test coverage of matrix/lib

test(matrix): add unit tests for matrix

---

blake3-air/src/columns.rs
circle/src/point.rs
koala-bear/src/poseidon2.rs
mersenne-31/src/x86_64_avx512/poseidon2.rs
monty-31/src/x86_64_avx512/packing.rs

chore: fix some typos in comment

---

air/src/air.rs
challenger/src/lib.rs
goldilocks/Cargo.toml
matrix/src/dense.rs
uni-stark/src/check_constraints.rs
uni-stark/src/folder.rs

Small cargo fix.
Ran into a few clippy complaints as well on the way so I fixed them as well.

AVX2 Goldilocks Missing Poseidon import.

---

keccak-air/src/air.rs
monty-31/src/dft/mod.rs

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

README.md

Hi there! I've updated README.md with enhanced wording clarity, hope it helps in some shape of form.

fix: multiple typos of different importance

---

goldilocks/src/data_traits.rs
goldilocks/src/extension.rs
goldilocks/src/goldilocks.rs
goldilocks/src/lib.rs

Aligned with other fields impl
- [monty-31](https://github.com/Plonky3/Plonky3/blob/39d318295574c4df137a15fd048b1215ca8d7b60/monty-31/src/monty_31.rs#L445-L451)
- [KoalaBear](https://github.com/Plonky3/Plonky3/blob/39d318295574c4df137a15fd048b1215ca8d7b60/koala-bear/src/koala_bear.rs#L69-L80)

Refactor Goldilocks two-adic implementation

---

Cargo.toml

Import `itertools` and `tracing` as `no_std`

---

.github/workflows/ci.yml

Add embedded target to CI

---

field/src/helpers.rs
field/tests/helpers_test.rs

Should close https://github.com/Plonky3/Plonky3/issues/356

field helpers: add unit tests

---

challenger/src/duplex_challenger.rs

More unit tests to test small isolated situations

challenger: more granularity in unit tests

---

commit/src/pcs.rs

No code changes, just added comments.
Trying to merge the large batch of comments in #776 one file at a time.

Add comments to Pcs trait

---

field/src/extension/binomial_extension.rs

Shares a little code with #845, gets a `35%` speed up in the cost/speed of squaring.

Perf: Custom code for Quintic Square 

---

field/src/extension/binomial_extension.rs

Roughly a `40%` speedup for the BabyBear Binomial Extension of degree 4 though inverses should still be avoided in almost all cases as they are always slow.
We also get a negligible speed up for degree 2 binomial extensions (`~3%`)

Perf: Custom code for inverse in quartic field extension.

---

interpolation/src/lib.rs

Porting some of the comments in #776 over. No code changes but I did add a TODO for a possible way to speed up this code if we need to.

Add comments to Interpolation code

---

commit/src/domain.rs
commit/src/pcs.rs
fri/src/hiding_pcs.rs
uni-stark/src/prover.rs

Addressing Issue #857.
Also added some comments to the prover at the same time to explain what the code is doing.

Move split_evals and split_domains into commit_quotient and add comments

---

Cargo.toml
field-testing/src/bench_func.rs
keccak/benches/bench_keccak.rs
util/benches/bit_reverse.rs

After https://github.com/bheisler/criterion.rs/pull/860

deps: bump criterion

---

merkle-tree/src/merkle_tree.rs

@SyxtonPrime I've started to study this function and add documentation to clarify each line. 
After switching to Poseidon in WHIR, it seems that this leaf hashing part (using now Poseidon and not Keccak anymore) can become a bottleneck. I didn't find any obvious improvement in the first pass but it would be nice if we could think about better parallelisation, SIMD or any other improvement of the strategies to speedup this part with Poseidon. I don't know which part is easier to improve for now:
- Poseidon implementation
- Hasher implementation
- Or the merkle tree directly
I've no precise numbers for now but it would be nice to keep an eye on this.

merkle tree: full documentation for `first_digest_layer`

---

dft/src/radix_2_small_batch.rs

Open to debate, but I find directly accessing the pairs of pairs in `{Double,Triple}LayerBlockDecomposition` to be no less readable than translating first into the `hi_lo_hi_lo` representation (though neither is very clear). Removing this extra layer of redirection also reduces the complexity somewhat, though the line count only went down by about 46 since some reformatting made some single lines into multiple lines.
Also removed the unnecessary dependency on a generic parameter as mentioned in another comment.

Remove the hi-ho-hi-ho structs

---

uni-stark/src/folder.rs

I guess it's part of #776 i dunno
@SyxtonPrime i've noticed your PR about adding comments to FRI and UNISTARK folders so i've made comments to  uni-stark/src/folder.rs
i'll be willing to do more in the future, just made this one as a sample, to know if you actually like it

docs: Add comprehensive documentation to constraint folder implementation

---

fri/tests/pcs.rs
uni-stark/tests/mul_air.rs

It gives a nice speedup and I don't think the loss of coverage should be too significant.

Shrink some test sizes

---

baby-bear/src/baby_bear.rs
baby-bear/src/extension_test.rs
bn254/src/bn254.rs
koala-bear/src/extension_test.rs
koala-bear/src/koala_bear.rs

Some people were asking for these and they are easy to add.
Will update multiplication/squaring/inversion methods in a different PR.

Adding Degree 8 extensions for KoalaBear and BabyBear.

---

field/src/extension/binomial_extension.rs
field/src/extension/mod.rs
field/src/packed/aarch64_neon.rs
field/src/packed/no_packing.rs
field/src/packed/x86_64_avx.rs
monty-31/src/extension.rs
monty-31/src/monty_31.rs
monty-31/src/utils.rs

Completely identical to #980 but with subtraction instead of addition.
Briefly checking the timings indicates that they are identical to the addition timings.

Speed Up Extension Field Subtraction

---

mersenne-31/src/aarch64_neon/packing.rs

This change adds a custom halve implementation to PackedMersenne31Neon using NEON intrinsics instead of the default trait fallback that multiplies by 1/2. It computes (val + ((val & 1) * P)) >> 1 per lane using a branchless sequence: build an odd-lane mask with vtstq_u32, select P via vandq_u32, and apply vhaddq_u32 to perform the halving add and shift. This matches the project’s approach used in other NEON code, avoids an unnecessary multiplication, and preserves the existing 0..=P representation. No other logic or files were modified, and the change passes lints.

mersenne-31: Implement NEON-optimized halve for PackedMersenne31Neon
