challenger/src/lib.rs
field/src/field.rs

We plan to avoid `generic_const_exprs`, so can't use an array here, but a slice should be fine I think.

as_base_slice

---

.github/workflows/ci.yml
field/src/packed.rs
util/src/lib.rs

`cargo test` runs some tests that `cargo test --all-targets` does not run.  See https://github.com/rust-lang/cargo/issues/6669 tracks this issues.  Specifically, doc tests.
This PR adds running the latter to our CI/CD, to ensure that a simple `cargo test` will work.
This PR also marks parts of the documentation that look like tests to cargo, but actually aren't meant to be tests.

Fix `cargo test`

---

commit/src/adapters/multi_from_uni_pcs.rs
commit/src/adapters/uni_from_multi_pcs.rs
commit/src/pcs.rs
fri/src/proof.rs
fri/src/verifier.rs
ldt/src/lib.rs
matrix/src/dense.rs
matrix/src/lib.rs
merkle-tree/src/lib.rs
multi-stark/src/config.rs
multi-stark/src/prover.rs
tensor-pcs/src/tensor_pcs.rs
uni-stark/src/config.rs
uni-stark/src/prover.rs

And remove the methods for reading committed data. I think in the future we can pass borrowed matrix types instead.

Let PCS take any `MatrixRows`

---

challenger/src/hash_challenger.rs

Following #27, we add further test coverage for a hash challenger.

test: hash challenger test coverage

---

README.md

Update README to provide guidance for external contributors with a particular view to managing the burden on PR reviewers.

Guidance for external contributors

---

.github/workflows/ci.yml

`--all-targets` seems to include them. And if we don't use `--all-targets`, we don't seem to need `--doc`.

Don't run benches on CI

---

baby-bear/src/baby_bear.rs

A few optimizations for Baby Bear arithmetic. Tbh the biggest thing here is `#[inline]`s

Optimize Baby Bear arithmetic

---

baby-bear/src/aarch64_neon.rs

The compiler's being a bit too clever and generating subtraction code (also used in multiplication) that's slower than my intrinsics.
I don't like this hack, but it does actually make a significant difference in performance (~10% for mul and ~20% for sub).

Prevent the compiler applying unhelpful optimizations (NEON Baby Bear)

---

dft/src/lib.rs
dft/src/radix_2_bowers.rs
dft/src/util.rs
mds/Cargo.toml
mds/src/coset_mds.rs
mds/src/lib.rs
poseidon/benches/poseidon.rs

This is almost like calling `Radix2Bowers`'s `coset_lde` with `added_bits=0`. I tried to reuse that code, but couldn't get comparable speeds. I haven't dug into the asm but I think there seem to be a couple issues:
- The compiler fails to do constant propagation, even in some cases which seem like they should be easy. This is why I explicitly precomputed `weights`. Ideally we'd compute them in `permute_mut` and constant propagation would make them immediate values, but it wasn't being done.
- I guess there are some range checks, and loops over matrix columns, that the compiler can't eliminate unless it inlines some large methods.
I think we may want the two implementations may diverge anyway, e.g. since `Radix2Bowers` is designed to be applied to matrices, we can vectorize over columns. …

Coset MDS implementation

---

field/src/field.rs
poseidon/src/lib.rs

This doesn't necessarily feel like the right solution, but in my builds it does seem to speed up Poseidon benchmarks significantly.
OTOH @unzvfu earlier found that the compiler seemed to be specializing the `exp_u64` code for constant arguments as one would hope. So we should probably look into this more. Not sure if it's a compiler difference (I'm using a recent nightly and targeting M1) or due to differences in the call sites.

`exp_const_u64`

---

fri/src/prover.rs
ldt/src/quotient.rs
uni-stark/tests/mul_air.rs

- Avoid allocations in `QuotientMatrix::row`
- Compute `1 / (x - opened_point)` once per row, rather than for each column (we could also do batch inversion, but I think this is good enough for now)

FRI performance fixes

---

commit/src/mmcs.rs
fri/src/fold_even_odd.rs
fri/src/prover.rs
ldt/src/quotient.rs
matrix/src/lib.rs
merkle-tree/src/lib.rs
uni-stark/tests/mul_air.rs

We were (wrongly) skipping committing after folding if there were no matrices to fold in.

Fix FRI commit phase

---

field/src/field.rs

Comment on the portability issues in `{as,from}_base_slice()`.

---

baby-bear/src/baby_bear.rs
field-testing/src/lib.rs
field/src/extension/cubic.rs
field/src/extension/mod.rs
field/src/extension/quadratic.rs
field/src/field.rs
field/src/lib.rs
goldilocks/src/lib.rs
mersenne-31/src/complex.rs
mersenne-31/src/extension.rs
mersenne-31/src/lib.rs

What has been Added:
1. Define trait Frobenius, OEF, and OptimalExtendable according to Plonky2 (mod.rs)
2. Define QuadraticOef and CubicOef with default implementation and distribution trait (quadratic.rs, cubic.rs)
3. Define quadratic and cubic extension for Mersenne31Complex (For simplicity, I used w=(i+2) for quadratic extension and w=5i for cubic extension) (extension.rs)
4. Copy two tests from Plonky2 and synthesis them in field_testing and update tests for all defined fields
Question:
Do we need another optional trait for Frobenuis? Created a new issue https://github.com/Plonky3/Plonky3/issues/90

Define Extension Field for Mersenne 31

---

field/src/extension/mod.rs

It seems like this may have been intended for defining trivial extension fields? But we also have a blanket impl declaring each field a trivial extension of itself, which seems more direct (there's no irreducible polynomial involved).

Remove blanket `OptimallyExtendable` impl

---

mersenne-31/src/complex.rs

This PR ensures that the generators for the full multiplicative group, as well as for its 2-adic subgroup, of the "complex" quadratic extension of the Mersenne31 field are the same as the generators described in the comments above them.
Also tidy up an misplaced and overly detailed comment.

Fix Mersenne31 complex generators

---

baby-bear/src/baby_bear.rs
field/src/field.rs
mds/Cargo.toml
mds/benches/mds.rs
mds/src/coset_mds.rs
mds/src/integrated_coset_mds.rs
mds/src/lib.rs
mersenne-31/src/lib.rs

Like `CosetMds`, with a few differences:
- (Bit reversed, a la Bowers) DIF + DIT rather than DIT + DIF
- We skip bit reversals of the inputs and outputs
- We don't weight by `1/N`, since this doesn't affect the MDS property
- We integrate the coset shifts into the DIF's twiddle factors
Also change `CosetMds` to precompute twiddles.

`IntegratedCosetMds`

---

field/src/extension/cubic.rs
field/src/extension/mod.rs
field/src/extension/quadratic.rs
mersenne-31/src/extension.rs

Rename symbols before we define other extension fields.
OptimallyExtendable ->BinomialExtendable
XXXOef -> XXXBEF.
Note: We can still define OEF for QuinticExtension and TesseracticExtension of baby bear
in https://github.com/Plonky3/Plonky3/issues/52 for faster computing of the inverse.

rename symbols for extension field.

---

field/src/extension/mod.rs
goldilocks/src/extension.rs
goldilocks/src/lib.rs
mersenne-31/src/extension.rs

extension field for goldilocks with binomial irreducible poly x^2-7
parameters come from plonky2.
Remove the DTH root from BinomialExtendable since this is not well defined for Bef (e.g., it seems it should be w^(p^2-1/ord) for the extension field of mersenne31complex). Since it is not used in the current implementation, I quickly removed it in this PR. I will reintroduce it when defining OEF(https://github.com/Plonky3/Plonky3/issues/113), which uses the Dth_root in the frobenuis function.

quadratic extension field for goldlilocks

---

mersenne-31/src/lib.rs

Today seems to be a good day. Improved the addition chain for inversion in M31. Saves 1 operation again.
For some reason running the benchmark on my computer for this (minor) improvement is giving a 25% speed increase but that seem ridiculous. I'd expect roughly a 5% improvement again.

Found a better addition chain for M31 too!

---

baby-bear/benches/root_7.rs
baby-bear/src/baby_bear.rs
field/src/array.rs
field/src/exponentiation.rs
field/src/field.rs
field/src/helpers.rs
field/src/lib.rs
goldilocks/benches/root_7.rs
goldilocks/src/lib.rs
mersenne-31/benches/root_5.rs
mersenne-31/src/lib.rs
rescue/src/inverse_sbox.rs
rescue/src/rescue.rs

Doing operations like exponentiation on `FieldArray` lets us do the same computation to be done in a different order (assuming the compiler preserves it), potentially enabling better instruction-level parallelism.
Results seem mixed but better overall. E.g. `BabyBear` width 16 gets ~6% slower, width 24 gets ~40% faster. Probably crossing some inlining or unrolling threshold in LLVM?

`FieldArray`

---

air/src/air.rs
baby-bear/src/aarch64_neon.rs
baby-bear/src/baby_bear.rs
field/src/array.rs
field/src/extension/cubic.rs
field/src/extension/quadratic.rs
field/src/field.rs
field/src/packed.rs
field/src/symbolic.rs
goldilocks/src/lib.rs
mersenne-31/src/complex.rs
mersenne-31/src/lib.rs

The main change is to merge `AbstractField` and `AbstractionOf`, simplifying the trait hierarchy.
Previously `AbstractField` didn't know what concrete field it was an abstraction of; now it does via an associated type `F`. This lets us write code like this in `AbstractField`
```rust
fn exp_u64(&self, power: u64) -> Self {
Self::F::exp_u64_generic(self.clone(), power)
}
```
which was the original motivation for this change. It's a bit of a strange API, but it lets us override `exp_u64_generic` with addition chains that are relevant to a particular field, and have those optimized addition chains used for all abstractions of that field, such as `FieldArray`.

`AbstractField` changes

---

README.md
dft/Cargo.toml
dft/benches/fft.rs
dft/src/testing.rs
dft/src/traits.rs
mersenne-31/Cargo.toml
mersenne-31/src/complex.rs
mersenne-31/src/dft.rs
mersenne-31/src/lib.rs

This PR implements the discrete Fourier transform over `Mersenne31`. It does so by packing a `Mersenne31` DFT of length `n` into a `Mersenne31Complex` DFT of length `n/2`. Some pre/post-processing is necessary so that the result of the transform behaves as expected wrt the convolution theorem etc. For the maths behind this I followed [this blog post](https://www.robinscheibler.org/2013/02/13/real-fft.html).
Notes:
- This is currently quite slow, even compared to what we might have expected. For example, this DFT is, respectively, about 5.5x, 4x, and 2.5x slower on vectors of length 2^14, 2^16, and 2^18, than the same sized DFT on `BabyBear`. Without thinking about it deeply I would have expected a 2x slowdown across the board (since multiplication is about 4x more expensive but the DFT …

Mersenne31 Fourier transform

---

baby-bear/src/aarch64_neon.rs
challenger/src/duplex_challenger.rs
field/src/array.rs
field/src/field.rs
mds/benches/mds.rs
mds/src/coset_mds.rs
mds/src/lib.rs
mersenne-31/src/complex.rs
poseidon2/src/diffusion.rs
symmetric/src/permutation.rs

So it can be used with `PackedField`s, and/or possibly `FieldArray` (which could use `F::Packing` later) if we need more instruction-level parallelism.
If there are no concerns, I'll make similar changes to other MDS impls, arithmetic hash impls, etc.
`IntegratedCosetMds` seems to take ~100ns with `BabyBear` and ~120ns with `PackedBabyBearNeon` (on M1), so seems promising in terms of potential throughput increases.

Generalize `CosetMds` to work with an `AbstractField`

---

challenger/src/duplex_challenger.rs
keccak/src/lib.rs
mds/src/babybear.rs
mds/src/coset_mds.rs
mds/src/goldilocks.rs
mds/src/integrated_coset_mds.rs
mds/src/lib.rs
mds/src/mersenne31.rs
monolith/src/monolith_mds.rs
poseidon/src/lib.rs
poseidon2/src/babybear.rs
poseidon2/src/diffusion.rs
poseidon2/src/goldilocks.rs
poseidon2/src/lib.rs
rescue/src/rescue.rs
symmetric/src/permutation.rs
symmetric/src/sponge.rs

`CryptographicPermutation<[T; N]>` works fine; `ArrayPermutation` was adding boilerplate without much benefit.

Remove `ArrayPermutation`

---

challenger/src/duplex_challenger.rs
keccak/src/lib.rs
mds/src/babybear.rs
mds/src/coset_mds.rs
mds/src/goldilocks.rs
mds/src/integrated_coset_mds.rs
mds/src/lib.rs
mds/src/mersenne31.rs
monolith/src/monolith_mds.rs
poseidon/benches/poseidon.rs
poseidon/src/lib.rs
poseidon2/benches/poseidon2.rs
poseidon2/src/babybear.rs
poseidon2/src/diffusion.rs
poseidon2/src/goldilocks.rs
poseidon2/src/lib.rs
rescue/benches/rescue.rs
rescue/src/rescue.rs
symmetric/src/permutation.rs

So that e.g. (simple, linear) MDS permutations can't be used in constructions like `PaddingFreeSponge`; the type checker will now prevent it.

Separate `Permutation` and `CryptographicPermutation` traits

---

keccak/src/lib.rs
mds/src/babybear.rs
mds/src/goldilocks.rs
mds/src/mersenne31.rs
monolith/src/monolith_mds.rs
poseidon/src/lib.rs
poseidon2/src/babybear.rs
poseidon2/src/goldilocks.rs
poseidon2/src/lib.rs
rescue/src/rescue.rs
symmetric/src/permutation.rs

To encourage direct impls of the latter. If compilers were smarter, it wouldn't matter, but in practice this seems to speed up things like Poseidon2 a nontrivial amount.

Default impl of `permute` rather than `permute_mut`

---

baby-bear/src/aarch64_neon.rs
baby-bear/src/baby_bear.rs
dft/benches/fft.rs
dft/src/naive.rs
dft/src/radix_2_bowers.rs
dft/src/radix_2_dit.rs
dft/src/radix_2_dit_parallel.rs
dft/src/testing.rs
field-testing/src/lib.rs
field/src/array.rs
field/src/extension/cubic.rs
field/src/extension/quadratic.rs
field/src/field.rs
field/src/symbolic.rs
fri/src/fold_even_odd.rs
goldilocks/src/lib.rs
interpolation/src/lib.rs
lde/src/naive.rs
ldt/src/ldt_based_pcs.rs
ldt/src/quotient.rs
mds/src/coset_mds.rs
mds/src/integrated_coset_mds.rs
mersenne-31/src/complex.rs
mersenne-31/src/dft.rs
mersenne-31/src/lib.rs
uni-stark/src/decompose.rs
uni-stark/src/prover.rs
uni-stark/src/verifier.rs
uni-stark/src/zerofier_coset.rs

- `multiplicative_group_generator()` -> `generator()` - it's less clear but "multiplicative group" just seems rather long, particularly if we include it in other methods (`power_of_two_multiplicative_group_generator()`?).
- Remove `power_of_two_generator()` (the one that generates the entire group) - it wasn't used except by the default impl.
- Rename `primitive_root_of_unity()` -> `two_adic_generator()` for consistent terminology.

Tweak generator methods in field APIs

---

commit/src/mmcs.rs
ldt/src/quotient.rs
merkle-tree/src/lib.rs

Addresses #70.
Summary of changes:
- added doc comments to `MMCS` interface
- changed `verify_batch` function signature to take a slice instead of an owned `Vec` (discussed with @dlubarov offline)
- added `PartialEq` bound for `D` in `MerkleMMCS` (needed to check roots match in `verify_batch`)
- made bounds consistent for `D` between `MerkleMMCS`, `MerkleTree`, and impls
- finished implementation of `open_batch`
- finished implementation of `verify_batch`
- added height property check to `MerkleTree::new`
- added more tests to `MerkleMMCS`

Finish `MerkleMMCS` Implementation

---

poseidon/benches/poseidon.rs
poseidon/src/lib.rs
poseidon2/src/lib.rs
rescue/benches/rescue.rs
rescue/src/rescue.rs

So a particular permutation struct type is not tied to a particular `AbstractField`, only the underlying concrete field. This lets a single permutation object impl e.g. `CryptographicPermutation<F::Packing>` as well as `CryptographicPermutation<F>` simultaneously.

Further generalize permutations

---

fri/Cargo.toml
fri/benches/fold_even_odd.rs
fri/src/fold_even_odd.rs
fri/src/lib.rs

addresses #140
summary of changes:
- make `fold_even_odd` `pub` (needed for bench)
- added benchmark for `fold_even_odd`.

add benchmark for `fold_even_odd`

---

field/src/field.rs
field/src/helpers.rs
util/src/lib.rs

Some simple fixes to some of clippy's more stringent demands (not currently enforced by CI, but still a good idea).
I wanted to add those to https://github.com/Plonky3/Plonky3/pull/145 but you were faster than me.
I'm using the following command to get some more hints from clippy:
```bash
cargo clippy --all-features --all-targets -- \
-D warnings \
-D clippy::pedantic \
-A clippy::inline-always \
-A clippy::similar-names \
-A clippy::module-name-repetitions \
-A clippy::missing-errors-doc \
-A clippy::missing-panics-doc
```

Make clippy even happier

---

baby-bear/src/baby_bear.rs
baby-bear/src/extension.rs
baby-bear/src/lib.rs
field/src/extension/binomial_extension.rs
field/src/extension/mod.rs
field/src/helpers.rs
goldilocks/src/extension.rs
mersenne-31/src/extension.rs

As discussed in https://github.com/Plonky3/Plonky3/pull/116, implement a general binomial extended field.
For simplification, `Frobenuis` trait is implemented for all `BinomialExtendable`.
Babybear's extension field(https://github.com/Plonky3/Plonky3/issues/113) is also implemented.
QuadraticBef and CubicBef are kept for now until we have a proper benchmark(https://github.com/Plonky3/Plonky3/issues/130) to discuss whether we need those implementations.
https://github.com/Plonky3/Plonky3/pull/116 can be closed if this PR is merged

Generalized extension field

---

dft/src/butterflies.rs
dft/src/radix_2_bowers.rs
dft/src/radix_2_dit.rs
dft/src/radix_2_dit_parallel.rs
matrix/src/dense.rs

This PR enhances the performance of DFT radix2 bowers by parallelizing the dit and dif butterfly methods across matrix rows in row-major form. Benchmarks indicate above 3x speed improvements. For instance, 
| Bench Name | Previous Execution Time (ms) | New Execution Time (ms) | Improvement Factor |
|------------|------------------------------|-------------------------|--------------------|
| `fft::<p3_goldilocks::Goldilocks, p3_dft::radix_2_dit::Radix2Dit, 100>/65536` | ~168 | 50.986 | ~3.3x |
| `fft::<p3_baby_bear::baby_bear::BabyBear, p3_dft::radix_2_dit::Radix2Dit, 100>/262144` | ~101 | 50.808 | ~2 |
| `m31_fft::<p3_dft::radix_2_dit::Radix2Dit, 100>/262144` | ~800 | 259.91 | ~3.13 |
However, our methods applied to the logic in `radix_2_dit_parallel.rs` exhibited increased execution …

feat: parallellize radix2 bowers

---

baby-bear/src/extension.rs
baby-bear/src/lib.rs
field/src/extension/binomial_extension.rs

Clippy didn't like the way it was building up a string.

Tweak `Display` impl of `BinomialExtensionField`

---

field/src/field.rs
fri/Cargo.toml
fri/src/fold_even_odd.rs

Summary of changes:
- use `F::Packing` in `fold_even_odd`, padding to the nearest multiple of `F::Packing::WIDTH` and truncating the result if necessary.
- add `PackedPowers`, a version of `Powers` that's more or less a "chunked" version of `Powers`, where the chunks are packed field elements.
- add a very basic test for `fold_even_odd`
Resulted in a significant (~3.5-4x) speedup for`BabyBear`, and small changes for other fields (which don't yet have vectorized impls)
For instance, on my M1 MBP, I get the following results for `fold_even_odd` size 2^16:
| field               | before (mean) | after (mean) | change           |
|---------------------|---------------|--------------|------------------|
| `BabyBear`          | 193.02 µs     | 45.240 µs    | -76.552% (~4.2x) |
| `Goldilocks` …

vectorize `fold_even_odd`

---

baby-bear/src/extension.rs
field-testing/src/lib.rs
field/src/extension/binomial_extension.rs
field/src/extension/mod.rs
goldilocks/src/extension.rs
mersenne-31/src/extension.rs

1. Design `HasTwoAdicBinomialExtension<D>` as an extension to `BinomialExtendable`; Implement `TwoAdicField` for `BinomialExtensionField` if base field Implement `HasTwoAdicBinomialExtension<D>`
2. Implement `HasTwoAdicBinomialExtension<D>` for all BinomialExtendable Fields
3. Add tests for two adic extension fields, including self-consistency and base field consistency.

impl two-adic trait for BEF

---

baby-bear/src/extension.rs
field/src/extension/binomial_extension.rs
field/src/extension/mod.rs
goldilocks/src/extension.rs
mersenne-31/src/extension.rs

To match `AbstractField::generator()` (it was renamed somewhat recently).

Rename ext_multiplicative_group_generator -> ext_generator

---

brakedown/src/standard_fast.rs
lde/src/lib.rs
lde/src/naive.rs
mersenne-31/src/lib.rs
reed-solomon/src/lib.rs

Fix the issue pointed out by @LKY-stephen in https://github.com/Plonky3/Plonky3/issues/159#issuecomment-1783743133
Also mark the LDE crate deprecated, I think it should be replaced by the `dft` APIs.

Fix naive LDE

---

commit/src/pcs.rs
fri/src/prover.rs
ldt/src/ldt_based_pcs.rs
ldt/src/quotient.rs
uni-stark/src/decompose.rs
uni-stark/src/prover.rs
uni-stark/src/verifier.rs

The quotient poly is computed from the trace's LDE over the *coset*, but `commit_batch` does not expect its input to be shifted. Also, the quotient parts need to be reduced with zeta instead of the root of unity.
As a proof of concept, I put a DFT -> unshift -> IDFT into the prover. This gets the test passing, is obviously not very efficient. I tried opening quotient_chunks at `(zeta * shift.inverse())^quotient_bits` instead of `zeta^quotient_bits`, but I couldn't get it to work. Maybe `commit_batch` can take a parameter for the shift to apply?
Not intended to merge, just for discussion!

Fix uni-stark quotient

---

uni-stark/src/proof.rs
uni-stark/src/prover.rs
uni-stark/src/verifier.rs

Currently, the degree bits in uni stark verifier seem to be hardcoded. This hack is to pass them from prover to verifier. Note that such a modification might not be secure as a protocol, and hence is to be removed as plonky3 gets updated

Pass degree bits to verifier

---

uni-stark/src/folder.rs
uni-stark/src/zerofier_coset.rs

Making these methods public makes it easier for projects trying to use individual components in `uni-stark`.

feat: make lagrange_basis_unnormalized + folders in uni-stark pub

---

brakedown/src/brakedown_code.rs

Not an extensive test cover by any means, I was having certain difficulties in coming up with simple enough tests for the `encode_batch` for `brakedown code`'s. Happy to receive any feedback on how to improve the test suite.

test: adds a simple testing suite to the brakedown crate

---

commit/src/pcs.rs
matrix/src/strided.rs
uni-stark/src/prover.rs
uni-stark/tests/mul_air.rs

Previously we were evaluating the quotient polynomial over the same domain that trace LDEs were defined over. However, it's valid and sometimes useful to let them diverge, i.e. with a larger blowup factor to minimize FRI queries.
It's also occasionally useful to have the opposite - a quotient whose degree exceeds our (committed) blowup factor. In that case we'd do the larger LDE for quotient evaluation, but Merklize a strided view of it, to speed up the commitment. However, this is a bit more annoying to support, and probably less frequently useful.
Fixes #188.

Fix the domain we evaluate the quotient over

---

keccak-air/src/air.rs
keccak-air/src/columns.rs
keccak-air/src/generation.rs

There was a bug where an array was treated as having `x, y, z` order rather than `y, x, z` order.
Also made a few other index-related tweaks while I'm here.

Fix Keccak AIR

---

fri/tests/fri.rs
keccak-air/examples/prove_baby_bear_keccak.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_goldilocks_keccak.rs
uni-stark/tests/mul_air.rs

Hi folks, I was reading the code lately, and I noticed some minor typos in testing related to Poseidon2, on SBox alpha, which should be the smallest positive integer satisfying gcd(p - 1, alpha) = 1. I believe this setting should derive from https://eprint.iacr.org/2019/458.pdf under section 2.3, s-box layer.
I went through the codebase and fixed alphas for Poseidon2 permutation instantiations over Goldilocks or BabyBear fields, in both cases the minimum alpha should be 7 rather than 5, if I calculated correctly.
Please let me know your thoughts on this minor PR, thanks.

Minor: Fixing alpha in sbox for BabyBear and Goldilocks in Poseidon2

---

commit/src/adapters/extension_mmcs.rs

The extension matrix width should be 1/Dth of the inner matrix width

Fix extension matrix width

---

maybe-rayon/src/lib.rs
maybe-rayon/src/serial.rs
uni-stark/Cargo.toml
uni-stark/src/decompose.rs

This PR introduces parallel processing logic for computing a generalized form of the even-odd decomposition for polynomials.
To evaluate the performance gains we run the proving `prove_baby_bear_keccak` example. With parallelization we obtain
```
INFO     generate Keccak trace [ 389ms | 100.00% ]
INFO     prove [ 1.67s | 50.05% / 100.00% ]
INFO     ┝━ commit to trace data [ 350ms | 8.88% / 21.01% ]
INFO     │  ┕━ compute all coset LDEs [ 202ms | 12.13% ]
INFO     ┝━ compute quotient polynomial [ 83.6ms | 5.02% ]
INFO     ┝━ decompose and flatten quotient [ 827µs | 0.05% ]
INFO     ┝━ commit to quotient poly chunks [ 4.55ms | 0.20% / 0.27% ]
INFO     │  ┕━ compute all coset LDEs [ 1.18ms | 0.07% ]
INFO     ┕━ prove batch opening [ 393ms | 0.16% / 23.59% ]
INFO        ┝━ compute opened …
```

parallelize polynomial decompose method

---

uni-stark/src/check_constraints.rs
uni-stark/src/symbolic_builder.rs
uni-stark/src/symbolic_expression.rs
uni-stark/src/verifier.rs

It was visiting the same `SymbolicExpression`s repeatedly in some cases. Probably best to just compute it upfront when we construct each `SymbolicExpression`.

Fix slow `degree_multiple()` code

---

fri/src/two_adic_pcs.rs
fri/tests/pcs.rs

Fixes https://github.com/Plonky3/Plonky3/pull/239
When reconstructing the reduced quotient from the original openings, it was computing the $X$ for $$\frac{p(X)-p(z)}{X-z}$$ from `log_max_height` instead of `log_height`. This has been fixed, which also includes right shifting to reduce the index appropriately.
Also included the test from #239, with fewer rounds and POW bits so it goes faster, and another test to make sure the order of matrices with different heights doesn't matter.

Fix fri multi deg

---

fri/src/verifier.rs

The current checks work when `log_blowup` is 1, but fail with larger blowups. I think this should be the right generalization?

Fix the final checks in the FRI verifier

---

baby-bear/src/x86_64_avx2.rs
mersenne-31/src/aarch64_neon.rs
mersenne-31/src/x86_64_avx2.rs

These were missed in the recent AVX PRs #214 and #221 but are used for benchmarking in the `mds` crate. The implementation was just copied from the existing one for BabyBear on Neon.
Aside: As this trait happens to be implemented for all `Field`s, I wonder if it's worth making it mandatory?

Add random distributions for fields vectorisation

---

keccak-air/Cargo.toml
keccak-air/examples/prove_goldilocks_poseidon.rs

Benchmark for Poseidon hash in Goldilocks field is added.
You can test it using `RUST_LOG=info cargo run --example prove_goldilocks_poseidon --release --features parallel`

add prove_goldilocks_poseidon example in keccak-air

---

air/src/virtual_column.rs

This PR replaces the `Vec<(PairCol, F)>` of column weights in the virtual column struct to a clone-on-write smart pointer `Cow<'a, [(PairCol, F)]>`. This allows us to have both vector instances and static slice instances of the virtual column struct.

Convert `VirtualPairCol` internal to a `Cow` pointer instead of `Vec`

---

uni-stark/src/folder.rs
uni-stark/src/verifier.rs

It seems more correct, enables AIRs that declare field-based constraints, and matches Valida & SP1.

Set `F` to the base field in `VerifierConstraintFolder`

---

baby-bear/src/aarch64_neon.rs
baby-bear/src/baby_bear.rs
baby-bear/src/x86_64_avx2.rs
baby-bear/src/x86_64_avx512.rs

I found a way to shave 1 instruction off Baby Bear multiplication in NEON, increasing the throughput by 14%.
As an added bonus, this version uses the 32-bit Montgomery form (that we use everywhere else), instead of the 31-bit form that NEON was previously using, so it avoids the weird fragmentation.
AND the 32-bit Monty form is a bit faster in scalar instructions too, so those should get a lil bit faster.

Faster Baby Bear multiplication on ARM/NEON

---

fri/src/two_adic_pcs.rs
fri/tests/pcs.rs

"Global" in the sense that it's the max for all FRI inputs, not just for all matrices under a certain commitment.
Fixes #250.

FRI PCS adjust indices based on the "global" max height

---

baby-bear/src/aarch64_neon.rs

A cube for NEON Baby Bear that's a bit faster. It performs the usual `val.square() * val`, but we avoid the final reduction into [0, ..., P) when squaring, saving 2 instructions (so going from 13 to 11).

(ARM/NEON) faster Baby Bear cube

---

field/src/field.rs

Fix #292. Add some more thorough documentation, in line with the sibling functions that also expose internal representation.

Fix issue 292

---

air/src/air.rs
uni-stark/src/check_constraints.rs
uni-stark/src/folder.rs
uni-stark/src/symbolic_builder.rs
uni-stark/src/symbolic_expression.rs
uni-stark/src/symbolic_variable.rs

It has been mentioned that uni-stark may support permutation traces. If this is the case, I think the symbolic variables and expressions could be shared between uni-stark, sp1, and Valida. 
Add an enum `Entry` to describe whether the variable is a public input, preprocessed trace,  main trace, permutation trace, public values, or challenges.

feat: add public, preprocessed, and permutation to uni-stark symbolic

---

air/src/two_row_matrix.rs
air/src/virtual_column.rs
baby-bear/src/baby_bear.rs
baby-bear/src/mds.rs
bn254-fr/src/lib.rs
challenger/src/serializing_challenger.rs
circle/src/domain.rs
commit/src/adapters/extension_mmcs.rs
fri/src/config.rs
fri/src/two_adic_pcs.rs
goldilocks/src/lib.rs
matrix/src/dense.rs
merkle-tree/src/mmcs.rs
monolith/src/monolith.rs
reed-solomon/src/lib.rs
rescue/src/sbox.rs
symmetric/src/compression.rs
symmetric/src/serializing_hasher.rs
symmetric/src/sponge.rs
uni-stark/src/config.rs
uni-stark/src/symbolic_expression.rs
uni-stark/src/symbolic_variable.rs
uni-stark/tests/fib_air.rs
util/src/lib.rs

- Transformed a large number of methods and functions across different libraries to constant functions including `new`, `to_monty_64`, `from_monty` and more.
- Enhances performance by utilizing constant functions in Rust, which are evaluated at compile time where possible.

refactor: Convert multiple functions to `const` functions

---

poseidon2/Cargo.toml
poseidon2/benches/poseidon2.rs
poseidon2/src/lib.rs
poseidon2/src/round_numbers.rs

Adding in round numbers so that new instances of poseidon2 can be created which automatically use the optimal round numbers for the prime, width, D triple.
Currently this is unused outside of the benchmarks but in a future PR we will start to propagate this throughout the code.

Round Numbers for Poseidon2

---

baby-bear/src/aarch64_neon/mod.rs
baby-bear/src/aarch64_neon/poseidon2.rs
baby-bear/src/poseidon2.rs
baby-bear/src/x86_64_avx2/mod.rs
baby-bear/src/x86_64_avx2/poseidon2.rs
baby-bear/src/x86_64_avx512/mod.rs
baby-bear/src/x86_64_avx512/poseidon2.rs

As opposed to defining DiffusionMatrixBabyBear for any abstract field over BabyBear, we split it out. This will allow for architecture specific implementations.

Separating arch specific poseidon2 for Babybear

---

air/src/air.rs

Making permutation challenges their own variable instead of `EF`. This is necessary for recursion and could be used for symbolic evaluations in the future as well.

feat: make permutation challenges a variable

---

keccak-air/Cargo.toml

Since we don't actually need any config beyond the default; this shouldn't change anything.

Remove example config

---

baby-bear/src/poseidon2.rs
bn254-fr/src/poseidon2.rs
goldilocks/src/poseidon2.rs
poseidon2/src/lib.rs
poseidon2/src/matrix.rs

We can improve the External Linear layer to require only 9 additions and 2 doubles as opposed to 10 additions and 4 doubles.
Only a small speed up (Roughly 2-5%) but no point leaving simple improvements on the table.
Currently still supporting both options to give the option to match our implementation with the Horizon Labs implementation.

Better External Linear Layer

---

uni-stark/tests/fib_air.rs

The test `fib_air.rs::test_incorrect_public_values()` in the `uni-stark` crate fails in release builds because relies on being run in a debug build to return the expected result; however this was not enforced in its metadata. This PR adds the missing directive.
@dlubarov Please confirm that this is the intended behaviour of the test; in particular that the code is not supposed to panic in release builds. Thanks!

Disable test that only makes sense in debug builds

---

merkle-tree/src/merkle_tree.rs

Since `digest_layers` cannot be empty. Thanks Jasper for pointing it out.

Simplify `prev_layer`

---

uni-stark/tests/mul_air.rs

These were taking the bulk of the time in our test suite. I think we shouldn't lose too much in terms of coverage with smaller domains, and it's really convenient being able to run the whole test suite (in debug mode, with no inlining etc) in a few seconds.

Smaller MulAir tests

---

circle/src/cfft.rs
dft/src/radix_2_bowers.rs
dft/src/radix_2_dit.rs
dft/src/radix_2_dit_parallel.rs
matrix/src/dense.rs

To reflect the current behavior; we could add a non-exact variant later if useful.

`par_row_chunks_mut` -> `par_row_chunks_exact_mut`

---

baby-bear/src/aarch64_neon/poseidon2.rs
baby-bear/src/poseidon2.rs
baby-bear/src/x86_64_avx2/poseidon2.rs
baby-bear/src/x86_64_avx512/poseidon2.rs
fri/tests/fri.rs
fri/tests/pcs.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
merkle-tree/benches/merkle_tree.rs
merkle-tree/src/mmcs.rs
poseidon2/benches/poseidon2.rs
uni-stark/tests/fib_air.rs
uni-stark/tests/mul_air.rs

BabyBear is written with a double capital in all other cases. Just getting DiffusionMatrixBabyBear to follow this convention.

Simple Renaming

---

mersenne-31/src/aarch64_neon/poseidon2.rs
mersenne-31/src/poseidon2.rs
mersenne-31/src/x86_64_avx2/poseidon2.rs
mersenne-31/src/x86_64_avx512/poseidon2.rs
poseidon2/benches/poseidon2.rs

The main purpose of this PR is to add support for Poseidon2 for arrays of M31 elements of length 24.
In addition to that, I've restructured the file slightly to better match the corresponding poseidon2 file in BabyBear.
I've also updated the testing suite to avoid the need for saving several large constant arrays in there. 
Note that the reference to https://github.com/0xPolygonZero/hash-constants on line 123 of mersenne-31/src/poseidon2.rs is slightly premature. I plan to add to that repository a file implementing Poseidon2 in sage and generating the expected values for the tests (Both here and for BabyBear/Goldilocks) sometime this week but haven't quite finished it.

Posiedon2 mersenne31 width 24

---

uni-stark/src/prover.rs
uni-stark/src/symbolic_builder.rs
uni-stark/src/verifier.rs

As we added preprocessing and public values to `SymbolicExpression` it would be useful to have `SymbolicBuilder ` implement `PairBuilder `.

feat(UniStark): Implement `PairBuilder` for `SymbolicBuilder`

---

koala-bear/src/koala_bear.rs

Somehow missed this initially. 31 is not a generator but 3 is.

Fix multiplicative generator of KoalaBear

---

keccak-air/src/air.rs
keccak-air/src/columns.rs
keccak-air/src/generation.rs

Also remove postimage, which isn't needed; we can use the usual row/step state since we don't need to copy it from one row to the next (since only final rows are exported)

Add missing constraint for Keccak preimage matching A (round input)

---

bn254-fr/src/lib.rs
field-testing/Cargo.toml
field-testing/src/lib.rs
field/Cargo.toml
field/src/field.rs
field/src/helpers.rs

Only `Bn254Fr` has a nontrivial `sqrt(largest_factor)`, so I hardcoded its factorization for now. It could be quickly inferred using other algorithms, but might be overkill.

Multiplicative group orders using naive trial division

---

challenger/src/duplex_challenger.rs
challenger/src/grinding_challenger.rs
fri/tests/fri.rs
fri/tests/pcs.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_goldilocks_poseidon.rs
uni-stark/tests/fib_air.rs
uni-stark/tests/mul_air.rs

Also removes one test which I thought was too much of a white-box test; it was almost a repeat of the challenger's internal logic.
Fixes #365 (cc @cyl19970726)

Fix `DuplexChallenger` so it doesn't overwrite capacity elements

---

circle/src/pcs.rs
commit/src/domain.rs
commit/src/pcs.rs
fri/src/two_adic_pcs.rs
matrix/src/lib.rs
merkle-tree/src/merkle_tree.rs

serde / Clone changes necessary to make vkey/pkeys in SP1 Clone/serde
* make `ProverData` struct Clone
* make `TwoAdicMultiplicativeCoset` struct serde
* make `Pcs::ProverData` Clone
* make `Dimensions` struct Clone

chore: add serde/clone derives

---

baby-bear/src/poseidon2.rs
koala-bear/src/poseidon2.rs
monty-31/Cargo.toml
monty-31/src/lib.rs
monty-31/src/poseidon2.rs

Stage 2 of slowly building the refactor. Note we are not merging with main, will do that in the far future.
Moving the poseidon2 implementation across to generic Monty-Field.
Currently there are 2 ways of going about it, either just providing methods or defining DiffusionMatrixMontyField31. This second way doesn't work yet due to the orphan rule but will work after we have moved the vector implementations across. (See the bottom of monty-31/src/poseidon2.rs.
Can decide later which method to keep later.

BabyBear - KoalaBear Refactor. Combining Poseidon2

---

uni-stark/src/prover.rs
uni-stark/src/verifier.rs

Per the audit. And add a note about potentially including other witness data later.

Include degree in the transcript

---

air/src/air.rs

Adding this method allows for the following pattern, which would be impossible at the moment since the `condition` field of `FilteredAirBuilder` is private.
```rust
pub trait CustomBuilder: AirBuilder {
fn assert_custom_when(&mut self, /*operands*/ condition: Option<Self::Expr>);
fn assert_custom(&mut self /*operands*/) {
self.assert_custom_when(/*operands*/ None);
}
}
impl<'a, AB: CustomBuilder> CustomBuilder for FilteredAirBuilder<'a, AB> {
fn assert_custom_when(&mut self, /*operands*/ outer_condition: Option<Self::Expr>) {
let condition = if let Some(outer_condition) = outer_condition {
outer_condition * self.condition()
} else {
self.condition()
};
self.inner.assert_custom_when(Some(condition))
}
}
struct ExampleChip {}
impl<AB: CustomBuilder> Air<AB> for ExampleChip {
fn eval(&self, …
```

Add `condition()` method on `FilteredAirBuilder`

---

baby-bear/src/aarch64_neon/packing.rs
baby-bear/src/x86_64_avx2/packing.rs
baby-bear/src/x86_64_avx512/packing.rs
field-testing/src/packedfield_testing.rs
koala-bear/src/aarch64_neon/packing.rs
koala-bear/src/x86_64_avx2/packing.rs
koala-bear/src/x86_64_avx512/packing.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx512/packing.rs

I think these simplifications resolve all the outstanding issues with #381 and tidy the code still further.
I have put the code with the `zeros` parameter in a second commit. I'm not convinced it should be part of the test suite, since it is only used by the `mersenne-31` crate. Might be better to do those specific tests just in that crate.

Simplify parameters to packed test macro

---

baby-bear/src/mds.rs
baby-bear/src/poseidon2.rs
koala-bear/src/poseidon2.rs
monty-31/src/lib.rs
monty-31/src/mds.rs
monty-31/src/poseidon2.rs

_For consideration._
This removes some of the `PhantomData` that's been proliferating. Unfortunately some lines become quite ugly, though they might be fixable.
Note that many of the changes are just because `cargo fmt` wasn't run on the source branch.

Remove some PhantomData from Monty31 MDS stuff

---

baby-bear/src/aarch64_neon/poseidon2.rs
baby-bear/src/poseidon2.rs
baby-bear/src/x86_64_avx2/poseidon2.rs
baby-bear/src/x86_64_avx512/poseidon2.rs
fri/tests/fri.rs
fri/tests/pcs.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
koala-bear/src/aarch64_neon/poseidon2.rs
koala-bear/src/poseidon2.rs
koala-bear/src/x86_64_avx2/poseidon2.rs
koala-bear/src/x86_64_avx512/poseidon2.rs
merkle-tree/benches/merkle_tree.rs
merkle-tree/src/mmcs.rs
monty-31/src/aarch64_neon/poseidon2.rs
monty-31/src/monty_31.rs
monty-31/src/poseidon2.rs
monty-31/src/x86_64_avx2/poseidon2.rs
monty-31/src/x86_64_avx512/poseidon2.rs
uni-stark/tests/fib_air.rs
uni-stark/tests/mul_air.rs

Possible Poseidon2 refactor for Monty31 fields.
It's not 100% clear to me if this is the right approach but this cuts down the amount of code so might be worthwhile.
The main downsides are that it involves a couple of pieces of PhantomData and some rather awkwardly names traits. The upside is that it moves the vast majority of the Poseidon2 field specific code into the Monty-31 crate and lets us make the "new_monty" function pub(crate) instead of pub.

Possible Poseidon2 refactor for Monty31 fields

---

circle/src/pcs.rs
fri/src/prover.rs
fri/src/two_adic_pcs.rs
fri/src/verifier.rs

There are some challenger related complications here, since the `SerializingChallenger`s don't impl `CanObserve` for extension fields, and doing so creates a theoretical conflict with `Hash`.
The workaround I'm proposing here is to bring back `FieldChallenger` and use its extension field methods. The downside is that the core FRI code now needs to know about the base field `Val`, so we can work with `FieldChallenger<Val>`.

Observe the final polynomial in FRI

---

keccak-air/examples/prove_baby_bear_keccak.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_goldilocks_keccak.rs
keccak-air/examples/prove_goldilocks_poseidon.rs
keccak-air/examples/prove_m31_keccak.rs
keccak-air/examples/prove_m31_poseidon2.rs
merkle-tree/src/lib.rs
merkle-tree/src/mmcs.rs
uni-stark/src/config.rs
uni-stark/src/verifier.rs
uni-stark/tests/mul_air.rs

Somewhat related to the first issue in the audit. Not sure if this is exploitable, but enforcing this should simplify the tree hash collision resistance argument.

Enforce that Merkle proofs must have the expected shape

---

matrix/src/dense.rs

`row_slices` is a non-parallel version of `par_row_slices`. Also non-mut analogues of `par_row_chunks_mut` and `par_row_chunks_exact_mut`.

[matrix] Add useful row iterator methods to DenseMatrix

---

keccak-air/src/air.rs

Added bool checks for `c`, `a_prime`, and `a_prime_prime_0_0_bits` elements.

fix: added bool checks in keccak air

---

bn254-fr/Cargo.toml
bn254-fr/src/lib.rs
bn254-fr/src/poseidon2.rs
keccak-air/Cargo.toml
keccak-air/examples/prove_baby_bear_poseidon2.rs
uni-stark/src/config.rs

Switches the `Bn254Fr` field to internally use the [halo2curves](https://crates.io/crates/halo2curves) implementation of `Fr`, which still implements the `ff` trait but has more optimized [implementations](https://github.com/privacy-scaling-explorations/halo2curves/blob/main/derive/src/field/arith.rs) of field arithmetic, which I believe are now fairly mature and well-used. There is also a feature "asm" for x86 assembly optimized implementations of field arithmetic.
Also implements `TwoAdicField` for `Bn254Fr` so it can be used as the `Val` (base field) for uni-stark if desired.
A note on serialization:
- I assume that plonky3 prefers serializations that are more optimized for speed, so I switched the serialization to serialize the raw internal bytes format of the field elements, which is …

chore: use `halo2curves` for BN254 `Fr` and implement `TwoAdicField`

---

Cargo.toml
keccak-air/Cargo.toml
keccak-air/examples/prove_baby_bear_sha256.rs
keccak-air/examples/prove_goldilocks_sha256.rs
keccak-air/examples/prove_m31_sha256.rs
sha256/Cargo.toml
sha256/src/lib.rs

Adds `CryptographicHasher` implementation for SHA2-256 in a separate `sha256` crate, essentially parallel to the `blake3` crate. I don't think it's possible to implement `CryptographicPermutation` since the internals of the hash are not exposed in the `sha2` crate.
I added some more examples to the `keccak-air` crate using this hasher as `ByteHash`.

feat: add `CryptographicHasher` implementation for SHA2-256

---

keccak-air/examples/prove_baby_bear_sha256_compress.rs
sha256/Cargo.toml
sha256/src/lib.rs

Since the SHA256 block size is 64 bytes, in a binary Merkle tree the 2-to-1 hashing would require 2 blocks due to padding. However if we treat SHA256 without padding as a pseudo-compression function, then the 2-to-1 compression would use only 1 block.
I added another example in `keccak-air` where `MyCompress = Sha256Compress` to show the usage. Unfortunately when I ran it locally there was essentially no difference in the prover speed, which was surprising to me.

feat: SHA-256 pseudo-compression 2-to-1 function

---

keccak-air/Cargo.toml

The asm feature in the sha-256 crate does not support windows. Just moving this from a default to an optionally enabled feature so that main can be compiled on windows again.
Someone with a mac/linux machine should check that the asm feature is working properly before we merge this.

move asm to a feature as opposed to default.

---

poseidon2/benches/poseidon2.rs

Slightly modifying the Poseidon2 benching functions to use the associated packed fields (if available).
I'm going to start pushing some Neon/AVX2/AVX512 specialized code for poseidon2 and in production we should always be hashing packed fields so it makes sense to focus the benchmarking just on the packed field case. You can still benchmark the non packed case simply by compiling without target-cpu=native or with target-cpu=something which doesn't support Neon/AVX2/AVX512.
I've also removed the benchmarks for KoalaBear with D = 5, 7. The D = 3 is the fastest (particularly after we write specialized code) and so there isn't really a good reason to leave the default as benching all three options. (It's also easy to modify the file anyway if we want to bench the D = 5, 7 cases for some …

Clean up Poseidon2 Benching

---

keccak-air/Cargo.toml
keccak-air/examples/prove_koala_bear_poseidon2.rs

Add a new example using the KoalaBear field.
Currently the timing is pretty similar to BabyBear but this should change after we implement specialized vectorization for Poseidon2.

Add a KoalaBear to prove examples

---

circle/src/pcs.rs
uni-stark/src/prover.rs

PCS should have unified tracing info message.
circle pcs print `open`, while two_adic_pcs does not print
```
RUST_LOG=info cargo run --example prove_baby_bear_keccak --release --features parallel
INFO     prove [ 1.04s | 0.86% / 100.00% ]
INFO     ┝━ infer log of constraint degree [ 5.64ms | 0.54% ]
INFO     ┝━ commit to trace data [ 519ms | 29.22% / 50.13% ]
INFO     │  ┕━ coset_lde_batch [ 216ms | 20.91% ] dims: 2633x32768
INFO     ┝━ compute quotient polynomial [ 306ms | 29.60% ]
INFO     ┝━ commit to quotient poly chunks [ 16.8ms | 0.80% / 1.62% ]
INFO     │  ┝━ coset_lde_batch [ 6.71ms | 0.65% ] dims: 4x32768
INFO     │  ┕━ coset_lde_batch [ 1.76ms | 0.17% ] dims: 4x32768
INFO     ┝━ compute_inverse_denominators [ 7.92ms | 0.77% ]
INFO     ┝━ reduce matrix quotient [ 65.4ms | 0.01% / …
```

better tracing info message

---

baby-bear/src/baby_bear.rs
circle/src/cfft.rs
circle/src/folding.rs
circle/src/pcs.rs

Remove redundant imports from `baby-bear` and `circle` crates. These are picked up in `nightly` but not `stable`.

Remove redundant imports

---

baby-bear/benches/bench_field.rs
baby-bear/benches/extension.rs
field-testing/src/bench_func.rs
goldilocks/benches/extension.rs
koala-bear/benches/bench_field.rs
mersenne-31/benches/extension.rs
monty-31/src/x86_64_avx2/packing.rs

This PR contains 2 things. Most of the changes are simply modifying the benchmark code to be able to bench the packed field implementations and adding in benchmarks for mul latency and throughput.
These benchmarks are then used to show the improvement that the 2 character change to monty-31/src/x86_64_avx2/packing.rs produces. Note that this change is valid as the bottom 32 bits of the things being subtracted are always identical (This is broadly the entire point of Monty multiplication). Despite being mathematically identical, there is a large difference in the code produced by the 2 almost identical implementations of Monty multiplication. (See https://godbolt.org/z/3W8M7Tv84 for the compiled code produced).
For such a small change, the output is somewhat dramatic. We get roughly a 30% …

Fixing strange AVX2 compilation bug

---

goldilocks/src/poseidon2.rs
keccak-air/examples/prove_m31_poseidon2.rs
mersenne-31/src/poseidon2.rs
mersenne-31/src/x86_64_avx2/poseidon2.rs
poseidon2/benches/poseidon2.rs
poseidon2/src/constants.rs
poseidon2/src/diffusion.rs
poseidon2/src/lib.rs
poseidon2/src/matrix.rs

We should be able to make Poseidon2 quite a bit faster (~10-20% for M31, 30-50% for BabyBear/KoalaBear) by making use of vectorization. Unfortunately, this will lead to some necessarily breaking API changes.
This PR introduces the suggested API changes and re-writes the Goldilocks and M31 Poseidon2 implementations using the new API but without any vectorization for now.
Plan is to do a similar thing to when developing the MONTY-31 field we do a bunch of PR requests onto a branch to help with the eventual large PR on main. This also lets us leave the branch slightly broken (e.g. it currently won't compile) as we slowly build things.
The broad goal of the API changes are to facilitate fast vectorized implementations.
There are 2 major problems with the current API which this PR seeks to …

Vectorizing Poseidon2: Initial API Changes

---

goldilocks/src/poseidon2.rs
mersenne-31/src/mersenne_31.rs
mersenne-31/src/poseidon2.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx2/poseidon2.rs
poseidon2/Cargo.toml
poseidon2/benches/poseidon2.rs
poseidon2/src/matrix.rs

We make a collection of changes to the Poseidon2 implementation for M31. This leads to around a 25%-30% improvement in performance with a slightly higher improvement for the WIDTH=24 case.  A rundown of the changes are as follows:
Custom s-box -- Currently x -> x^5 is being done by repeated multiplication and squaring, we can improve upon this by writing a custom function. In particular note that if we want to compute x^2, it equivalent to start with x in the range {0, ..., P} or {-P, ..., P}. Hence we don't need to fully elements into {0, ..., P} nearly as much. There is a minor drawback later on which is that it is slightly more complicated to reduce something in {-P^2, ..., P^2} but the benefit easily outweighs this negative.
Saving round constants as negatives -- Along the same lines …

AVX2 implementation for Poseidon2 for M31.

---

baby-bear/Cargo.toml
circle/Cargo.toml
commit/Cargo.toml
koala-bear/Cargo.toml
monolith/Cargo.toml
uni-stark/Cargo.toml

Just some tidying; used the output of `cargo +nightly udeps`.
(I left in the unused dependencies in `keccak-air` and `poseidon2-air`, since the examples in those crates are meant for experimenting with different parameters, and it would be annoying to adjust the dependencies each the time.)

Remove some unused dependencies

---

dft/src/radix_2_bowers.rs
dft/src/util.rs
matrix/src/dense.rs

This older one was single-threaded, although I don't notice the different much (haven't benched them in isolation).

Remove the old bit_reversed_zero_pad function

---

mds/Cargo.toml

Everywhere else uses version 0.13.0, but the `mds` package used 0.12.0 for no particular reason. This caused `itertools` was imported and compiled twice. Fixed by updating the `mds` import to use 0.13.0 too.

De-dup itertools versions

---

blake3/Cargo.toml
blake3/src/lib.rs
keccak/Cargo.toml
keccak/src/lib.rs
sha256/Cargo.toml
sha256/src/lib.rs
util/src/lib.rs

Most `hash_iter()` implementations are copypasta that includes an avoidable vector allocation. This PR introduces a "buffered iterator" that repeatedly calls the underlying hash update function with chunks of bytes from the input iterator. Improves performance of most `hash_iter()` calls by 10-20%.

Remove vector allocations in `hash_iter()` implementations

---

circle/src/pcs.rs
fri/tests/fri.rs
fri/tests/pcs.rs
keccak-air/examples/prove_baby_bear_keccak.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_baby_bear_sha256.rs
keccak-air/examples/prove_baby_bear_sha256_compress.rs
keccak-air/examples/prove_goldilocks_keccak.rs
keccak-air/examples/prove_goldilocks_poseidon.rs
keccak-air/examples/prove_goldilocks_sha256.rs
keccak-air/examples/prove_koala_bear_poseidon2.rs
keccak-air/examples/prove_m31_keccak.rs
keccak-air/examples/prove_m31_poseidon2.rs
keccak-air/examples/prove_m31_sha256.rs
merkle-tree/benches/merkle_tree.rs
merkle-tree/src/merkle_tree.rs
merkle-tree/src/mmcs.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_keccak.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_poseidon2.rs
uni-stark/tests/fib_air.rs
uni-stark/tests/mul_air.rs

The remaining uses of `PackedField` can easily be generalized to `PackedValue`, at which point this no longer has any field logic, hence the rename.

Slightly generalize Merkle tree

---

circle/src/folding.rs
circle/src/lib.rs
circle/src/pcs.rs
circle/src/proof.rs
circle/src/prover.rs
circle/src/verifier.rs

Such that regular FRI and circle FRI no longer share that code. Keeping `FriConfig`, `FriGenericConfig`, `FriError` shared for now; not sure if they'll diverge later.

Split FRI proof objects & logic

---

keccak-air/src/generation.rs
poseidon2-air/src/generation.rs
rescue/src/rescue.rs
util/src/lib.rs

div_ceil is now stabilized so we no longer need our own version in utils.
See: https://doc.rust-lang.org/std/primitive.u32.html#method.div_ceil
At some point we should similarly remove log2_ceil_u64/log2_ceil_usize as ilog2 is also standardized but this is slightly more annoying as the rounding is different (ilog2 rounds down instead of up).

Removing our custom impl of div_ceil.

---

goldilocks/src/lib.rs
mersenne-31/src/mersenne_31.rs

Somehow the base M31 and Goldilocks fields were missing `#[repr(transparent)]`!
Luckily this has had no effect so far but in principle this could break all the transmutes used in pack field code.

Adding repr(transparent) to M31 and Goldilocks 

---

field/src/field.rs
goldilocks/src/lib.rs
keccak-air/src/generation.rs
matrix/src/dense.rs
matrix/src/mul.rs
mersenne-31/src/mersenne_31.rs
monty-31/src/dft/mod.rs
monty-31/src/lib.rs
monty-31/src/monty_31.rs
poseidon2-air/src/generation.rs
uni-stark/tests/fib_air.rs
uni-stark/tests/mul_air.rs

This follows the transmutation approach @unzvfu used in #440, and applies it more broadly to some other places where we allocate zero vectors.

Add a `zero_vec` method in `Field`

---

field/src/extension/binomial_extension.rs
field/src/helpers.rs

This way it will boil down to a `vec![0u32; len * D]` which seems to avoid redundant zeroing.

Have `BinomialExtensionField` override `zero_vec`

---

field/src/extension/binomial_extension.rs
matrix/Cargo.toml
matrix/benches/columnwise_dot_product.rs
matrix/src/dense.rs
matrix/src/lib.rs
maybe-rayon/src/lib.rs

75% faster in both serial & parallel.
Still some gains on the table due to iterator chain overhead, I think. The proper solution is to specialize this even further in `DenseMatrix`.
More importantly, though, I need to rewrite `interpolate_coset` to take multiple points, and this should be a matrix-matrix product.

Vectorize columnwise_dot_product

---

field/Cargo.toml
field/src/batch_inverse.rs

This is sort of naive as it involves several separate instances of the batch inversion algorithm, resulting in several `inverse()` calls. It would be more optimal to have one big parallelized instance, with one big partial product tree made up of smaller per-thread trees, but that seems a bit annoying to code. Inversion isn't terribly expensive (especially for 32-bit fields) so the difference doesn't seem that important, but it could be worth revisiting at some point.
Separately, this should ideally be vectorized. I tried doing so with `F::Packing`, but it didn't help much as the most important callers use extension fields with trivial packings. We could use the `ExtensionPacking` approach, there are just some API complications.
This change alone reduces inversion costs from ~6% to ~1%, …

Parallelize batch inversion

---

goldilocks/src/x86_64_avx2/packing.rs
goldilocks/src/x86_64_avx512/packing.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx512/packing.rs
monty-31/src/x86_64_avx2/packing.rs
monty-31/src/x86_64_avx512/packing.rs

When PackedFieldPow2 was spun out of PackedField, this wasn't updated for the AVX2/AVX512 code for various fields (MontyField31, Mersenne31, Goldilocks).

Main currently breaks on AVX2 and AVX512

---

baby-bear/Cargo.toml
baby-bear/src/lib.rs
baby-bear/src/x86_64_avx2/poseidon2.rs
baby-bear/src/x86_64_avx512/poseidon2.rs
koala-bear/Cargo.toml
koala-bear/src/lib.rs
koala-bear/src/x86_64_avx2/poseidon2.rs
koala-bear/src/x86_64_avx512/poseidon2.rs
monty-31/src/data_traits.rs
monty-31/src/lib.rs
monty-31/src/no_packing/poseidon2.rs
monty-31/src/poseidon2.rs
monty-31/src/x86_64_avx2/poseidon2.rs
monty-31/src/x86_64_avx2/utils.rs
monty-31/src/x86_64_avx512/mod.rs
monty-31/src/x86_64_avx512/packing.rs
monty-31/src/x86_64_avx512/poseidon2.rs
monty-31/src/x86_64_avx512/utils.rs
poseidon2/Cargo.toml
poseidon2/src/matrix.rs

NOTE: This is not merging into main (for now). Will wait until all specialized impls (AVX2/AVX512/NEON, M31/MONTY31) are done before doing that.
Initial try was to basically copy/paste the AVX2 implementation but this ended up being a little complicated due to missing a few missing intrinsic. Hence I needed to rebuild the custom `-2^{-N}` multipliers in [monty-31/src/x86_64_avx512/utils.rs] and ended up getting rid of the `2^{-N}` multipliers, instead handling that change later by replacing an add by a sub. This had a side effect of forcing me to slightly update the specifications for add/sub and show that they can handle one input being equal to `P`.
When looking into Goldbolt I also noticed that some of the current AVX512 functions are not compiling correctly. To fix this I introduced a …

AVX512 implementation for Koala/BabyBear, Poseidon2

---

commit/src/mmcs.rs
keccak/src/avx2.rs
keccak/src/avx512.rs
mds/src/coset_mds.rs
mds/src/util.rs
monty-31/src/poseidon2.rs
symmetric/src/compression.rs
uni-stark/tests/fib_air.rs
util/src/lib.rs

My Clippy seems to be a slightly newer version than the one in our CI and so gives me a couple of silly errors.
None of these changes should have any effect on timing or anything. Most of them are fixing: [too_long_first_doc_paragraph ](https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph) which basically wants the first line of doc strings to be short. There are also a couple of [missing_transmute_annotations](https://rust-lang.github.io/rust-clippy/master/index.html#/missing_transmute_annotations) and [needless_range_loop](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_range_loop).
I've tried where possible to rewrite the doc comments with minimal changes to meaning. Let me know if I've messed one up.

Minor Changes to make Clippy happy

---

mersenne-31/src/poseidon2.rs
poseidon2-air/Cargo.toml
poseidon2-air/examples/prove_poseidon2_baby_bear_keccak.rs
poseidon2-air/examples/prove_poseidon2_m31_keccak.rs

Adding a pair of examples to prove Poseidon2 which use M31 and BabyBear respectively to allow a better comparison between different fields.
The BabyBear example is identical to the KoalaBear one except for the fact that we need an extra register for each s-box. This doubles the width of the trace and so BabyBear takes about 2x times as long as the equivalent KoalaBear example.
For M31 this means we switch to using the Circle stark instead of the standard stark as well as needing an extra register for each s-box. For now as the circle stark is less optimized, this example is 3x slower than the KoalaBear/

Add M31 and BabyBear examples for prove Poseidon2

---

keccak/src/avx2.rs
keccak/src/avx512.rs
keccak/src/lib.rs
keccak/src/neon.rs
keccak/src/sse2.rs

I know we don't usually bother supporting SSE, but this is such a simple change from AVX2 that it didn't take any time at all.
SSE2 is included as part of x86_64, so this code will be used on 64-bit x86 CPUs even if the user does not explicitly enable any features.

SSE2 implementation of Keccak

---

challenger/src/grinding_challenger.rs
challenger/src/multi_field_challenger.rs

Currently the rate is being set equal to the permutation width which is obviously bad. Added a different constant.

fix: multi-field challenger rate

---

uni-stark/src/symbolic_expression.rs
uni-stark/src/symbolic_variable.rs

Small refactor to combine different arithmetic operations over `SymbolicExpression` and `SymbolicVariable`. In particular, for each `Op = Add, Sub, Mul`, we replace the 8 implementations
```rust 
// expr * f
impl<F> Op<F> for SymbolicExpression<F> {}
// expr * var
impl<F> Op<SymbolicVariable<F>> for SymbolicExpression<F> {}
// expr * expr
impl<F> Op for SymbolicExpression<F> {}
// expr += f
impl<F> OpAssign<F> for SymbolicExpression<F> {}
// expr += expr
impl<F> OpAssign for SymbolicExpression<F> {}
// var + f
impl<F> Op<F> for SymbolicVariable<F> {}
// var + var
impl<F> Op for SymbolicVariable<F> {}
// var + expr
impl<F> Op<SymbolicExpression<F>> for SymbolicVariable<F> {}
```
with 3 generic ones that take advantage of `Into<SymbolicExpression<F>>`.
```rust 
// expr + {f, var, expr} …
```

refactor: Simplify implementation of symbolic arithmetic operations

---

matrix/src/extension.rs
matrix/src/lib.rs
merkle-tree/src/merkle_tree.rs
uni-stark/src/prover.rs

Currently vertically_packed_row is creating an expensive iterator which may repeatably run through rows of a given matrix.
We split vertically_packed_row into 2 entities. One which returns a single packed row and one which returns a pair of a packed row and a pack "next" row.
This gives around a 5-10% speed-up  to the examples prove_poseidon2_koala_bear_keccak and prove_poseidon2_m31_keccak. In particular "compute quotient polynomial" drops from ~16% to around 9%.

Speeding up Vertically_Packed_Row

---

poseidon2-air/examples/prove_poseidon2_baby_bear_keccak_zk.rs

Currently not compiling on msvc environments. Need to not load Jemalloc in those cases.

Minor Jemalloc Fix

---

merkle-tree/benches/merkle_tree.rs
merkle-tree/src/merkle_tree.rs
merkle-tree/src/mmcs.rs

When matrices have #rows != pow-of-two, there is no reason we should be padding to the next power of two and hashing all the zeros together. We can save prover time by avoiding hashing the trailing zeros.
These changes affect the root computation (the digest changes).
The API for opening & verification stay the same.
The changes make the code a bit less elegant.
Also note that if higher arity trees are ever introduced, the `_padded` lengths would need to change from even, to divisible by the arity (ariteven?).
The change is best illustrated with these two matrices: this exact test is included, see commit 62d02bcc373c016f2ec716fd98e9ac69b8cf6cfd which adds the test case for current construction (initially broken) and a59d70663c0e0580d79f5a3731785d7984b6e7e3 which fixes it to adapt to this …

perf: Avoid hashing together default digests (zeros) in MT construction

---

challenger/src/duplex_challenger.rs

A duplex should only output elements from the rate part of the state, not the capacity part.
Thanks Mirco / Least Authority for flagging.

Fix duplex outputs

---

field/src/extension/binomial_extension.rs
field/src/field.rs

We want to avoid calling two times `self.as_base_slice()` for perf reason so:
- We declare a variable
```rust
let base_slice = self.as_base_slice();
```
- We reuse this inside the method.

field: improve `ExtensionField::as_base`

---

goldilocks/src/goldilocks.rs
mersenne-31/src/mersenne_31.rs
monty-31/src/monty_31.rs

I think that in the proposed scenarios, it makes it more Rust idiomatic and less verbose

refactor: use `into` instead of `from` when possible

---

baby-bear/src/aarch64_neon/poseidon2.rs
baby-bear/src/poseidon2.rs
baby-bear/src/x86_64_avx512/poseidon2.rs
field/src/batch_inverse.rs
field/src/field.rs
field/src/helpers.rs
goldilocks/src/x86_64_avx512/mds.rs
goldilocks/src/x86_64_avx512/packing.rs
koala-bear/src/aarch64_neon/poseidon2.rs
koala-bear/src/poseidon2.rs
koala-bear/src/x86_64_avx512/poseidon2.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/aarch64_neon/poseidon2.rs
mersenne-31/src/poseidon2.rs
mersenne-31/src/x86_64_avx512/packing.rs
mersenne-31/src/x86_64_avx512/poseidon2.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/data_traits.rs
monty-31/src/poseidon2.rs
monty-31/src/x86_64_avx512/packing.rs

There are a few `AbstractField` imports left. This PR renames those to `FieldAlgebra`. Fixes build issues for neon

Fix: rename remaining `AbstractField`s as `FieldAlgebra`

---

fri/Cargo.toml
fri/src/hiding_pcs.rs
fri/src/lib.rs
matrix/src/horizontally_truncated.rs
matrix/src/lib.rs
poseidon2-air/examples/prove_poseidon2_baby_bear_keccak_zk.rs

This isn't the full thing yet, after this we need to blind each polynomial, adding randomness and padding to the next power of two.
In this approach, every input matrix gets extended with several random codewords. We might be able to get by with less, like at least grouping matrices of the same height and only extending one of them. But this seemed simplest in a way, and I suspect the performance difference won't be too important.

Hiding FRI PCS

---

commit/src/adapters/extension_mmcs.rs
matrix/src/extension.rs

The behaviour is the same as `inner_ref` but should be more Rust idiomatic.

matrix: implement `Deref` for `FlatMatrixView`

---

circle/src/point.rs
field/src/field.rs

Currently `try_div` is a wrapper around a one line function which is more informative as to what is actually going on. It's also basically never used. Given that, I think it's worth just removing this method as it's basically just recreating functionality which already exists with `try_inverse`.

Remove the method `try_div`

---

mersenne-31/src/dft.rs

This code is basically unused (so maybe we will just remove it at some point) but regardless `halve` should be vastly preferred over `div_2exp_u64(1)`.

Replace `div_2exp_u64(1)` by `halve()`

---

baby-bear/src/poseidon2.rs
monty-31/src/mds.rs

1. File: `baby-bear/src/poseidon2.rs`
- Original: `An implementation of the the matrix multiplications in the internal and external layers of Poseidon2.`
- Revised: `An implementation of the matrix multiplications in the internal and external layers of Poseidon2.`
- Reason: Removed the duplicate article "the" to correct the grammatical error.
2. File: `monty-31/src/mds.rs`
- Original: `singed_conv_32, singed_conv_16, singed_conv_8 so the`
- Revised: `signed_conv_32, signed_conv_16, signed_conv_8 so the`
- Reason: Corrected the spelling of "singed" to "signed" to accurately reflect the technical term for operations involving signed numbers.
These changes ensure that the documentation and comments are grammatically correct and technically accurate, enhancing the readability and …

Pull Request: Fix Documentation Typos

---

challenger/src/multi_field_challenger.rs
challenger/src/serializing_challenger.rs
field/src/field.rs
goldilocks/src/goldilocks.rs
mersenne-31/src/mersenne_31.rs
monty-31/src/monty_31.rs
symmetric/src/serializing_hasher.rs

Originally this was going to be part of the larger Field crate refactor but there are actually no API breaking changes here so we can just merge it now.
This PR add a method to both `PrimeField64` and `PrimeField32` called `to_unique_u64` and `to_unique_u32`. As can be inferred from the name, given a field element these output a unique `u64/u32`. Where unique means that two field elements output the same value if and only if they are equal. This is intended for use in hashing and allows us to hash `MontyField31` elements without needing to convert out of MONTY form.
Propagating these changes through to serializing_hasher.rs, this gives a very small speed up to proof times when using KECCAK. (`1-2%` as best).
Additionally, we make similar change to Serialization/Deserialization for …

Minor Improvements to Hashing and Serialization/Deserialization.

---

keccak-air/examples/prove_baby_bear_keccak.rs
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/examples/prove_baby_bear_sha256.rs
keccak-air/examples/prove_koala_bear_keccak.rs
keccak-air/examples/prove_koala_bear_poseidon2.rs
keccak-air/examples/prove_m31_poseidon2.rs

A few of the examples use the `RecursiveDft` but, currently for the trace dimensions, `Radix2DitParallel` is noticeably faster. Switching this gives a `10-20%` speed boost.
Similarly, when working with `Poseidon2`, we should be using the `WIDTH=24` hash where possible as its faster than running the `WIDTH=16` hash twice. This is the relevant comparison if we are compressing by hashing the union of `8` elements from the old state and padding to the width by new elements. This seems to give a further `5-10%` speed up.
Finally, we add an extra example, `prove_koala_bear_keccak`. This examples timing data should be essentially identical to `prove_baby_bear_keccak` but it's useful to have for completeness sake.

Optimizing the Prove KECCAK Examples.

---

poseidon2-air/examples/prove_poseidon2_baby_bear_keccak.rs
poseidon2-air/examples/prove_poseidon2_baby_bear_poseidon2.rs
poseidon2-air/examples/prove_poseidon2_m31_poseidon2.rs

I'm doing a pass through all our examples to try and get some benchmarks, and thought I'd try to make things a little more systematic while I do that.
The goal will be that all three of our large airs (`Poseidon2-AIR, KECCAK-AIR, Blake3-AIR`) to have one example for each `31` bit field `BabyBear, KoalaBear, M31` and choice of hash function `Keccak` vs `Poseidon2`.
Additionally, within each example we should be using whatever `FFT` is optimal.
This PR just handles the `Poseidon2-AIR`s. We add two new examples using `BabyBear/M31` with hash function `Poseidon2`. Additionally we fix a small bug in the current `BabyBear` example where the number of partial rounds is higher than it should be. This improves that example slightly.

Prove Poseidon2 Examples

---

field/src/extension/binomial_extension.rs
field/src/extension/mod.rs
field/src/extension/packed_binomial_extension.rs

Note this is not merging into main. The plan is to develop the Field crate refactor in a separate branch and then merge it all in in a single PR. This will avoid the need for a collection of small API breaking changes.
This change doesn't anything much right now but will become important for some of the future `FieldAlgebra` changes as it allows us to add impls between `BinomialExtensionField` and `PackedBinomialExtensionField`.
Currently these are impossible as its possible for `BinomialExtensionField` to be the same as its own packing.

Field Crate Refactor: Splitting PackedBinomialExtension into a separate struct.

---

blake3-air/Cargo.toml
blake3-air/examples/prove_blake3_baby_bear_poseidon2.rs
blake3-air/src/air.rs
keccak-air/Cargo.toml
keccak-air/examples/prove_baby_bear_poseidon2.rs
keccak-air/src/air.rs
poseidon2-air/examples/prove_poseidon2_baby_bear_keccak_zk.rs
poseidon2-air/examples/prove_poseidon2_baby_bear_poseidon2.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_keccak.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_poseidon2.rs
poseidon2-air/examples/prove_poseidon2_m31_keccak.rs
poseidon2-air/examples/prove_poseidon2_m31_poseidon2.rs
poseidon2-air/src/generation.rs
poseidon2-air/src/vectorized.rs
uni-stark/examples/prove_monty_31_keccak.rs

This means we can easily imply a methods for `Enum {Blake3Air, KeccakAir, Poseidon2Air}`.
I'll split off some of the code in prove_monty_31_keccak into another file in a future PR so we can have some equivalently easy to customize examples for other fields and merkle hash functions.

Add generate_trace_rows methods to all of our airs.

---

challenger/src/serializing_challenger.rs
keccak-air/examples/prove_goldilocks_keccak.rs

Updating the Goldilocks example to make use of the faster Keccak method. This gives around a `10%` speed up.
In order to do this we need to add a simple impl for `SerializingChallenger64` which was missing.
Hopefully in a future PR we can fold this into the customizable example in PR #576. This method for `SerializingChallenger64` will  need to be added in order to do that though so we just add it here.

Update Keccak method used in Goldilocks Example

---

challenger/src/serializing_challenger.rs

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `unofrmly` to `uniformly`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

koala-bear/src/koala_bear.rs
koala-bear/src/poseidon2.rs
monty-31/src/poseidon2.rs

Changed:
"implementation of the the matrix" -> "implementation of the matrix"
Removes redundant word for better readability.

Fix duplicate

---

poseidon2-air/src/constants.rs

Constructor for `RoundConstants` to allow for pre-generated constants to be used in `Poseidon2Air`. Also derives `Clone` for `RoundConstants` for easier use.

chore: constructor for poseidon2-air RoundConstants

---

baby-bear/src/aarch64_neon/packing.rs
commit/src/testing.rs
fri/src/two_adic_pcs.rs
merkle-tree/src/mmcs.rs

This eliminates a few sources of panics in the API, notably this removes an `.expect("fri error")` at the end of a failing call to `<TwoAdicFriPcs<Val, Dft, InputMmcs, FriMmcs> as Pcs<Challenge, Challenger>>::verify`. T
Contributes to #168.

Better error management in mmcs/two_adic_pcs

---

challenger/src/multi_field_challenger.rs

I noticed a change in behavior in `MultiField32Challenger::sample_bits` after recent `FieldAlgebra` refactors.
This line https://github.com/Plonky3/Plonky3/blob/784b7dd1fa87c1202e63350cc8182d7c5327a7af/challenger/src/multi_field_challenger.rs#L188 has been changed to use `to_unique_u32()`, which for Monty31 fields will use the monty reduced form and not the canonical form for bit sampling.
Since the main use case (AFAIK) of `MultiField32Challenger` is when you need to embed 31-bit fields into larger fields like `Bn254Fr`, it is very unwieldy to have to work with the Montgomery form. For example, I noticed this behavior when trying to update the plonky3 commit and it changed the FRI verifier's behavior.
I looked through the current other uses of `to_unique_u32` and I agree the use in …

fix: revert behavior of `MultiField32Challenger::sample_bits`

---

circle/src/domain.rs
circle/src/pcs.rs
examples/src/proofs.rs
merkle-tree/src/mmcs.rs

Eliminates a few sources of panics, uses more specific error types in places.
Continues #600, contributes to #168.

Better error management

---

goldilocks/src/goldilocks.rs
goldilocks/src/mds.rs
goldilocks/src/poseidon2.rs
goldilocks/src/x86_64_avx2/packing.rs
goldilocks/src/x86_64_avx512/packing.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/mds.rs
mersenne-31/src/mersenne_31.rs
mersenne-31/src/poseidon2.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx512/packing.rs
monolith/benches/permute.rs
monolith/src/monolith.rs

Minor clean up and making things more consistent. (Based on some comments on the larger refactor PR)
Monty31 already has a `new_array` method which avoids needing to use `.map`. This just defines the same method for `Mersenne31` and `Goldilocks`.
This shouldn't make any changes to the public API so we can do it here as opposed to needing to do it as part of a large API breaking change.

Add new_array methods for Goldilocks and Mersenne31

---

util/Cargo.toml
util/benches/bit_reverse.rs
util/src/lib.rs
util/src/transpose.rs

This imports the bit reversal implementation from Plonky2, focusing on `reverse_slice_index_bits`. FIxes #444.
This also imports some unit tests on the edge cases of `log2_strict_usize`, which were in the same file.
I have not tuned `BIG_T_SIZE` and `SMALL_ARR_SIZE` currently set for a rather conservative 64KB L1.
Values for bench machines are for M3 Max:
```
huitseeker@binky➜tmp/plonky3/util(add_tests)» sysctl -a | grep -Ee 'hw\.l[12].*?cachesize'                                                                                                                                          
hw.l1icachesize: 131072
hw.l1dcachesize: 65536
hw.l2cachesize: 4194304
```
For Ryzen 9950X:
```
huitseeker@sleipnir➜huitseeker/tmp/plonky3(add_tests)» lscpu | grep "cache" …
```

Optimize bit reversal

---

air/src/utils.rs
bn254-fr/src/lib.rs
field/src/array.rs
field/src/extension/binomial_extension.rs
field/src/field.rs
goldilocks/src/x86_64_avx2/packing.rs
goldilocks/src/x86_64_avx512/packing.rs
keccak-air/src/air.rs
keccak-air/src/columns.rs
keccak-air/src/constants.rs
keccak-air/src/generation.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx512/packing.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/monty_31.rs
monty-31/src/x86_64_avx2/packing.rs
monty-31/src/x86_64_avx512/packing.rs
uni-stark/src/symbolic_expression.rs

Two main changes here:
I removed the columns in the AIR for the export and preimage. Both of these are basically unused in AIR currently and don't seem to be serving a purpose. The preimage was just the input to the permutation copied to every row, but this input is already saved as the input to the very first row. Similarly, the export column seems to be able to be implied from the step flags. Let me know if you want me to re add in either of these.
The bigger change is a revamp over how the trace generation works. It's a lot faster to keep track of the current state as a `[[u64; 5]; 5]` array and then periodically convert each `u64` into `64` boolean values or `4`,  `16`-bit limbs. This cuts down the trace generation by about 85%. (On my machine generating the trace for `10922` …

Cleaning up KECCAK AIR and speeding up its trace generation.

---

baby-bear/src/extension.rs
challenger/src/duplex_challenger.rs
challenger/src/lib.rs
challenger/src/multi_field_challenger.rs
challenger/src/serializing_challenger.rs
circle/src/pcs.rs
circle/src/prover.rs
circle/src/verifier.rs
commit/src/adapters/extension_mmcs.rs
field-testing/src/lib.rs
field/src/extension/binomial_extension.rs
field/src/extension/packed_binomial_extension.rs
field/src/field.rs
fri/src/prover.rs
fri/src/two_adic_pcs.rs
fri/src/verifier.rs
fri/tests/fri.rs
fri/tests/pcs.rs
interpolation/src/lib.rs
koala-bear/src/extension.rs
matrix/src/dense.rs
matrix/src/extension.rs
matrix/src/lib.rs
uni-stark/src/prover.rs
uni-stark/src/verifier.rs

Note this is not merging into main. The plan is to develop the Field crate refactor in a separate branch and then merge it all in in a single PR. This will avoid the need for a collection of small API breaking changes.
The point of this PR is to do about the half the work required in order to delete the `FieldExtensionAlgebra` trait. Here we move most of it's functionality into a new trait: `Serializable<F>`. (I haven't yest deleted `FieldExtensionAlgebra` but will do that in a future PR before this merges onto main).
A struct `A` should implement `Serializable<F>` if it is naturally convertible to and from a collection of `F` elements. When `F` is a field and `A` some `FieldAlgebra` over `F`, implementing `Serializable<F>` corresponds to choosing a basis for `A`. This is used when we …

Field Crate Refactor: Emptying out the FieldExtensionAlgebra trait

---

examples/examples/prove_prime_field_31.rs

I was curious about the tradeoff between the number of columns / constraints vs trace length in Plonky3. I played around with the `prove_prime_field_31` example, obtaining [these results](https://docs.google.com/spreadsheets/d/1aXqmsJXC_qXBOxmfA7uqb-0UX-IFNlmhL9P-l8QWGkU/edit?usp=sharing).
I believe this change is needed though, to correctly compute the number of hashes when changing the `P2_VECTOR_LEN` constant.

Correct `num_hashes` computation for changing `P2_VECTOR_LEN`

---

circle/src/pcs.rs
fri/src/two_adic_pcs.rs

In the current PCS implementations, polynomial openings are not added to the transcript. As a result, it breaks soundness, a malicious prover can construct valid proofs for any gate by playing with quotient openings. This PR fixes the issue by adding openings to the transcript for both `TwoAdicPcs` and `CirclePcs`.
Also @levs57 and I demonstrated a simple attack to a mul gate [here](https://github.com/kilic/plonky3_unsound/tree/generalized)

Bug fix: observe openings

---

air/src/air.rs
commit/src/adapters/extension_mmcs.rs
field/src/extension/binomial_extension.rs
field/src/extension/complex.rs
field/src/extension/mod.rs
field/src/extension/packed_binomial_extension.rs
field/src/field.rs
field/src/packed.rs
matrix/src/dense.rs
matrix/src/extension.rs
matrix/src/lib.rs
uni-stark/src/verifier.rs

Note this is not merging into main. The plan is to develop the field crate refactor in a separate branch and then merge it all in in a single PR. This will avoid the need for a collection of small API breaking changes.
The point of this PR is to remove the FieldExtensionAlgebra trait. Instead we replace it by `PackedFieldExtension` which provides methods to produce a `PackedFieldExtension` element from a slice of `ExtensionField` elements as well as a iterator which computes the powers of a given element.
Additionally, we move a couple of methods from `Field` into `PackedField` where they more naturally live.

Field Crate Refactor: Remove the FieldExtensionAlgebra trait

---

fri/src/two_adic_pcs.rs

Currently for each opening point a trace matrix is compressed again with exactly same procedure. But we can compress once and cache it and use it for calculation of quotient values

Compress matrices once

---

field-testing/src/lib.rs
field/src/extension/packed_binomial_extension.rs

Note this is not merging into main. The plan is to develop the Field crate refactor in a separate branch and then merge it all in in a single PR. This will avoid the need for a collection of small API breaking changes.
This adds a couple of tests to check the functions: `as_unique_u32, as_canonical_u32` inside `PRIMEFIELD32` and `as_unique_u64, as_canonical_u64` inside `PRIMEFIELD64`. Could probably be made more comprehensive but better than nothing.

Field Crate Refactor: Increase test coverage.

---

blake3-air/src/air.rs
blake3-air/src/generation.rs
examples/src/airs.rs
examples/src/proofs.rs
keccak-air/examples/prove_baby_bear_sha256.rs
keccak-air/examples/prove_baby_bear_sha256_compress.rs
keccak-air/examples/prove_goldilocks_keccak.rs
keccak-air/examples/prove_goldilocks_poseidon2.rs
keccak-air/examples/prove_goldilocks_sha256.rs
keccak-air/examples/prove_m31_sha256.rs
keccak-air/src/air.rs
keccak-air/src/generation.rs
poseidon2-air/examples/prove_poseidon2_baby_bear_keccak_zk.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_keccak.rs
poseidon2-air/src/generation.rs
poseidon2-air/src/vectorized.rs

Currently, when using the `Radix2DitParallel` a surprisingly large amount of time (5 - 10% of full proof time) is spent by "reserve_exact" which takes the trace and reserves more space for the DFT to populate. Strangely, reserving this extra space is massively more expensive than the initial trace generation. (Like 5-6x worse). On the other hand, if we absorb reserving the extra space into the initial trace generation, the cost goes to 0.
Hence this PR adds an extra parameter to the `generate_trace_rows` functions which indicates how much extra capacity to reserve.
This gives a little over a `5%` speed up to the `Keccak` and `Blake` examples. The `Poseidon2` example is unchanged as this had already been implicitly implemented in that case.
The current solution is to call `F::zero_vec` to …

Add extra_capacity_bits argument to all trace generation

---

challenger/Cargo.toml
challenger/src/duplex_challenger.rs
challenger/src/grinding_challenger.rs
challenger/src/multi_field_challenger.rs
challenger/src/serializing_challenger.rs

While working on a Plonky3 implementation of some protocol, @Cesar199999 and I realised our prover was grinding way more bits than it should be able to and our verifier was happily accepting the witnesses. This boils down to the fact that, for `DuplexChallenger`s, grinding and verification resort to `sample_bits`, which contains two assertions:
```
debug_assert!(bits < (usize::BITS as usize));
debug_assert!((1 << bits) < F::ORDER_U64);
```
In our case, we were running a protocol where the configuration was asking the `DuplexChallenger` for a PoW of 131 bits. In release mode, none of the above assertions were being checked and the prover and verifier were secretly performing grinding (computation and verification) for (1 << 131) = 8 bits. This arithmetic overflow should be prevented by the …

Challenger sampled bits

---

keccak-air/src/air.rs
keccak-air/src/columns.rs
keccak-air/src/generation.rs

After discussions with @dlubarov, we are partially reverting the KECCAK-AIR changes we made a week or so ago, adding back in the `preimage` and `export` columns.
This makes the AIR a little slower `~(5-8%)` but is a little more realistic for the most common use case where it is handy to have the permutation input and output on the same row.

Partial Keccak-AIR revert

---

circle/src/pcs.rs
commit/src/pcs.rs
commit/src/testing.rs
fri/src/hiding_pcs.rs
fri/src/two_adic_pcs.rs

Raise the output of `get_evaluations_on_domain` to an associated type instead of `impl Matrix<..>`.
In response to issue #626

Add an associated type for `Pcs::get_evaluations_on_domain` 

---

circle/src/pcs.rs
commit/src/testing.rs
fri/src/two_adic_pcs.rs

This PR adds a single `debug_assert!` to each of `TwoAdicFriPcs::open()`, `CirclePcs::open()`,
and `TrivialPcs::open()`, verifying that for each round of batch openings, the vector of 
matrices to be opened has the same length as the vector of sets of opening points. Without this 
check, these functions will silently truncate the larger of these two vectors. This was resulting
in some hard-to-diagnose errors in Valida, where the number of matrices to open in each round 
varies (e.g. because some chips do not have a preprocessed trace).

Ensure vectors of matrices have same length as vectors of opening points

---

baby-bear/src/poseidon2.rs

Should close #662
@SyxtonPrime Here is my initial idea, tell me what you think, if you want for example to move the code to another file (because too many lines) or change the constants. I would say that we could do the same for the other types of fields that we have.

babybear: add default poseidon2 impl with rc

---

goldilocks/benches/extension.rs
mersenne-31/benches/extension.rs

This PR fixes a typo in benchmark function names where `qudratic` was incorrectly spelled instead of `quadratic`
**The changes include:**
- Renamed `bench_qudratic_extension` to `bench_quadratic_extension` in multiple benchmark files
- Updated corresponding function calls in `criterion_group! macros`
The fix ensures consistent and correct spelling across the codebase. This is a minor change that only affects function names and has no functional impact on the benchmarks themselves.
**Files modified:**
`main...kilavvy-Plonky3:main`
`mersenne-31/benches/extension.rs`

Fix typo in benchmark function names: qudratic -> quadratic

---

util/src/lib.rs
util/src/linear_map.rs

This deletes a few unused/uneeded methods and traits in the utils file:
- `transpose_in_place_square`: this is currently a wrapper for an identical (same name and arguments) function in `src/transpose`. So I've just deleted this. 
- `VecExt` : Right now this is only used in `1` place, and only one of it's routines are used. It seems clearner to just copy that routine over and delete this trait.
- `transpose_vec`: this is unused (and would be very slow). We usually operate on `RowMajorMatrices` instead of `Vec<Vec<F>>` anyway so I don't this this really has a use case. As such I'm deleting this as well.

Deleting some unused stuff from Utils

---

README.md
air/src/utils.rs
blake3-air/src/generation.rs
dft/src/radix_2_dit_parallel.rs
dft/src/traits.rs
field/src/integers.rs
fri/src/two_adic_pcs.rs
matrix/src/bitrev.rs
mersenne-31/src/poseidon2.rs
mersenne-31/src/x86_64_avx2/poseidon2.rs
mersenne-31/src/x86_64_avx512/packing.rs
mersenne-31/src/x86_64_avx512/poseidon2.rs
monty-31/src/dft/backward.rs
monty-31/src/dft/mod.rs
monty-31/src/x86_64_avx2/poseidon2.rs
monty-31/src/x86_64_avx512/packing.rs
monty-31/src/x86_64_avx512/poseidon2.rs

There has been a large increase in low effort PRs which simply fix a small typo (Or, often, suggest "fixes" which do not improve the relevant comment). These seem to be mostly bots likely looking for tokens awarded to ecosystem contributors so to avoid encouraging them, I've run though the suggested changes, added the ones which make sense to this PR and will close all of the bot PRs.
I've also added a line to the readme asking people to not submit PRs which simply fix a minor typo. This probably won't help with the bots but at least gives us something to point to.
Main Changes
- Removing duplicated words.
- Add license images to Readme.   (Happy to get rid of these if we don't want them).
- Fix spelling error: `Reversable -> Reversible` (This is technically an API breaking change but …

Minor fixes throughout codebase

---

goldilocks/src/extension.rs

I have implemented the Goldilocks quintic extension field, as defined in the [EcGFp5 paper](https://eprint.iacr.org/2022/274.pdf). This enhancement enables the definition of secure elliptic curves over Goldilocks, ensuring a 128-bit security level.
Note the extension order factorizes as:
```sage
2^32 * 3 * 5^2 * 17 * 257 * 45971 * 65537 * 255006435240067831 * 280083648770327405561 * 7053197395277272939628824863222181
```
so there is no need of implementing the `HasTwoAdicBinomialExtension` for this extension, as all the power-of-to order subgroups are defined over the base field.

Adding Goldilocks quintinc extension field

---

goldilocks/src/goldilocks.rs

Make the list of Goldilocks `two_adic` generators public. They can be accessed as `Goldilocks::TWO_ADIC_GENERATORS`.
This matches the situation for `BabyBear` and `KoalaBear` as the trait which stores their `two_adic` generators is also constant.

Make Goldilocks two_adic generators public. 

---

Cargo.toml
examples/Cargo.toml
examples/src/proofs.rs

There were some API changes in the jump from 1.3.3 to 2.0.0 so the bot was unable to do it by itself.

Updates Bincode requirement to 2.0.0

---

field-testing/src/lib.rs
field/src/extension/mod.rs
field/src/helpers.rs

There are a collection of functions in `field` which are basically never used (outside of testing themselves) and are definitely not optimized so we should probably just remove them.
There are two methods supporting addition on vectors of field elements:
- `add_vecs`: Compute v + w component wise.
- `sum_vecs`: Compute v + w + ... by calling `add_vecs` repeatedly.
If we want to support these, `add_vecs` should be summing the vectors as `PackedField` elements. Given how simple these are though, I think we should just delete them and let others implement them if they see fit.
There are a collection of methods supporting polynomials in the coefficient domain.
- `naive_poly_mul`: Multiply polynomials. (This is much slower than in the evaluation domain)
- `binomial_expand`: Expand a product of …

Remove some unused functions

---

Cargo.toml
commit/src/mmcs.rs
field/src/field.rs
field/src/integers.rs
field/src/packed.rs
monty-31/src/x86_64_avx2/poseidon2.rs
monty-31/src/x86_64_avx512/poseidon2.rs
poseidon2-air/src/generation.rs
poseidon2/src/external.rs
poseidon2/src/lib.rs
poseidon2/src/round_numbers.rs
rescue/Cargo.toml
rescue/src/util.rs
uni-stark/src/check_constraints.rs
uni-stark/src/folder.rs
uni-stark/src/symbolic_builder.rs

Following the spirit of #168 and the ensuing discussion, we should be trying to mostly avoid panicking.
While this is probably impossible (without compromising speed), we can at least mark functions which might panic with `# Panic` and give the conditions upon which panicking might occur. Ideally, for function whose performance is not critical, we should try and replace `panic!` by returning a result. (In particular we should probably do this for `Poseidon2::new_from_rng_128` but that looks a little painful so for now I've just marked that with a `# Panic`.
I've ignored any `panic!`'s which occur in test code as those are fine.
2 Specific comments:
- In `field/src/integers`, the `panic!` is only reached if `usize` is not the same size as any integer type (`u8, u16, u32, u64, u128`). As …

Add Panic documentation

---

Cargo.toml
field/Cargo.toml
rescue/Cargo.toml
rescue/src/rescue.rs
rescue/src/util.rs

The `num_rounds` function calculates the number of rounds that the Rescue Prime paper claims is necessary for a given security level. The original implementation was private, even though it's quite useful, so we've started by making it public. However the implementation also pulls in dependencies on bignum crates that can be avoided, and indeed must be avoided in order to remove dependency on `std` (ongoing work addressing #594).
This PR includes an function that directly approximates `log2(binomial(n, k))` thus avoiding the need to pass to bignums. The implementation depends on new functions for log2 and pow2, which are included to avoid depending on floating point libraries (this is required to address #594). The accuracy of all of these functions is a bit mediocre by usual standards, …

Reduce dependencies in Rescue by reimplementing `num_rounds`

---

field-testing/src/bench_func.rs

pr:https://github.com/Plonky3/Plonky3/pull/669 make some changes like:
```
for (column, weight) in self.column_weights.iter() { ->
for (column, weight) in &self.column_weights {
```
Maintain a consistent style instead of using explicit iteration methods
```
warning: it is more concise to loop over references to containers instead of using explicit iteration methods
--> field-testing/src/bench_func.rs:82:24
|
82 |             for row in input.iter_mut() {
|                        ^^^^^^^^^^^^^^^^ help: to write this more concisely, try: `&mut input`
```

Make Clippy Happy 

---

baby-bear/benches/bench_field.rs
circle/examples/lde.rs
examples/src/proofs.rs
fri/benches/fold_even_odd.rs
fri/tests/fri.rs
fri/tests/pcs.rs
goldilocks/benches/bench_field.rs
keccak-air/examples/prove_baby_bear_sha256.rs
keccak-air/examples/prove_baby_bear_sha256_compress.rs
keccak-air/examples/prove_goldilocks_keccak.rs
keccak-air/examples/prove_goldilocks_poseidon2.rs
keccak-air/examples/prove_goldilocks_sha256.rs
keccak-air/examples/prove_m31_sha256.rs
maybe-rayon/src/lib.rs
maybe-rayon/src/serial.rs
mds/benches/mds.rs
merkle-tree/benches/merkle_tree.rs
monolith/benches/permute.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/x86_64_avx512/packing.rs
poseidon/benches/poseidon.rs
poseidon2-air/examples/prove_poseidon2_baby_bear_keccak_zk.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_keccak.rs
rescue/benches/rescue.rs
uni-stark/tests/fib_air.rs
uni-stark/tests/mul_air.rs
util/src/lib.rs

Like it says on the tin; also adds `#![no_std]` to `maybe-rayon`, which had been overlooked. Continued work addressing #594.
Note that the `use core::blah` stuff in `maybe-rayon` isn't required when compiling on "typical" targets, but is required on embedded targets like `thumbv7em-none-eabi` for example.

Replace `std::` with `core::` where possible.

---

merkle-tree/src/merkle_tree.rs
merkle-tree/src/mmcs.rs

Adding some comments to `merkle-tree/mmcs`.
Was going through and trying to understand how the verifier worked in this instance and thought I'd slightly improve the comments as I did. I also gave the verification code a slight refactor. Changes:
- Currently we compute `max_height`, check it against `proof_length` and then, provided all the checks pass, sort the input matrices by height. It's a little simpler just to sort them first. This also lets us combine the two places which would return `return Err(EmptyBatch)`.
- When constructing a MerkleTree, we have a condition that matrices whose heights pad to the same power of two, must have equal heights. Currently the verifier does not check this so I've added that. (It's not completely clear to me if we need the verifier to check this or …

Add Comments to Merkle Tree with a minor Verifier refactor

---

poseidon2-air/Cargo.toml
poseidon2-air/examples/prove_poseidon2_baby_bear_keccak_zk.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_keccak.rs

Make the Jemalloc dependency inclusive on Unix-based systems (such as Linux and MacOSX), not exclusive of MICROS~1 systems. This is so that it won't be included as a dep on other more esoteric systems, like embedded targets.

Use Jemalloc when on Unix/MacOS, not when NOT on MICROS~1

---

Cargo.toml
blake3-air/src/generation.rs

Like it says on the tin.
Mysteriously, having made Blake3 `no_std` and compiling for `thumbv7em-none-eabi`, rustc complains about unchecked overflow of the right shifts in the Blake3 AIR. Hence I've made the desired shift behaviour explicit.

Make Blake3 and Sha3 `no_std`

---

Cargo.toml
bn254-fr/Cargo.toml
bn254-fr/src/lib.rs
bn254-fr/src/poseidon2.rs

Main change is to remove the completely redundant use of `OnceLock`.
I also moved the dependencies from the root `Cargo.toml` into the package's `Cargo.toml`, and I removed the redundant `ff` dependency (which is already included by `halo2curves`).

Make `bn254-fr` no_std

---

bn254-fr/src/poseidon2.rs

Add a custom internal layer multiplication for Bn254's poseidon2 implementation.
This avoids all multiplications and costs only `5` additions and `1` double. (As far as I can tell this should be optimal).
This seems to give a `~25%` speed up to the full Poseidon2 implementation. (Multiplications in `Bn254` are really expensive...)
(I asked co-pilot to review it as I'm curious about what it will say)

Improve bn254 Poseidon2

---

circle/src/pcs.rs
circle/src/verifier.rs
commit/src/testing.rs
fri/src/config.rs
fri/src/hiding_pcs.rs
fri/src/two_adic_pcs.rs
fri/src/verifier.rs
merkle-tree/src/hiding_mmcs.rs
merkle-tree/src/mmcs.rs
uni-stark/src/verifier.rs
uni-stark/tests/fib_air.rs
util/src/lib.rs
util/src/zip_eq.rs

This is not merging to `main`. This is a patch commit to branch `openvm-v1.0` that cherry-picks fix https://github.com/Plonky3/Plonky3/commit/367f76133c3e614f65e856ef21c4963237d6907d for https://github.com/Plonky3/Plonky3/security/advisories/GHSA-m23j-cj9m-ppg9 onto the commit https://github.com/Plonky3/Plonky3/commit/88d7f059500fd956a7c1eb121e08653e5974728d that OpenVM is using for v1.0.0. This commit is prior to the large `p3-field` trait refactors.
* Introducing `ZipEq` and Fixes to `fri/src/verifier`
* Fixing hiding_pcs, merkle_tree, mmcs.
Just got circle_stark stuff left to go.
* Fixing Circle Stark zip appearances
* cargo fmt
* Minor changes to testing.
* Fixing a couple more instances of zip/izip appearing.
* Remove unused ZipEqError
* Update to remove the need for raise_error.
* …

fix: Missing size checks in FRI

---

fri/src/two_adic_pcs.rs

We never use `mats` elsewhere so doing a `.collect_vec();` is a bit silly. (Noticed this as I was adding comments).

Tiny change to save an allocation in the `.open` method of TwoAdicPCS.

---

field/src/coset.rs

```
warning: this argument is a mutable reference, but not used mutably
--> field/src/coset.rs:185:22
|
185 |     fn generator_exp(&mut self, exp: usize) -> F {
|                      ^^^^^^^^^ help: consider changing to: `&self`
```

Remove needless reference mut

---

circle/src/deep_quotient.rs
field/src/extension/packed_binomial_extension.rs
field/src/packed.rs
fri/src/two_adic_pcs.rs
matrix/src/lib.rs

The primary goal here is to rework the prover slightly to avoid computing powers of `alpha` multiple times.
This turned out to be a little more complicated than I initially suspected and the cleanest approach I ended up finding was to add a couple of new methods to `PackedFieldExtension` allowing users to convert from an iterator of `PackedFieldExtension` elements to an iterator of `FieldExtension` elements and a method similar to `packed_powers` but handles the case where you only want to compute a finite number of powers while still making use of the packing.
I also had to rework `dot_ext_powers` to accept a vector of packed field elements instead of computing the packed field elements vector internally. (Note the previous implementation also contained a bug where it was computing far …

Minor prover refactor to remove duplicated computation

---

examples/src/airs.rs
examples/src/lib.rs
examples/src/tests.rs
poseidon2-air/src/air.rs
poseidon2-air/src/generation.rs

Adding a bunch of end-to-end tests for `VectorizedPoseidion2Air, Poseidon2Air, Blake3Air, KeccakAir`.
Tried to strike a balance between testing lots of different configurations (E.g. Field, Merkel hash, DFT) while not massively increasing the time it takes to test. These add between 30s and 1min to overall time taken to run the test configuration.

Adding some end to end tests

---

examples/src/proofs.rs
examples/src/types.rs
keccak-air/examples/prove_baby_bear_sha256.rs
keccak-air/examples/prove_baby_bear_sha256_compress.rs
keccak-air/examples/prove_goldilocks_keccak.rs
keccak-air/examples/prove_goldilocks_poseidon2.rs
keccak-air/examples/prove_goldilocks_sha256.rs
keccak-air/examples/prove_m31_sha256.rs
poseidon2-air/examples/prove_poseidon2_baby_bear_keccak_zk.rs
poseidon2-air/examples/prove_poseidon2_koala_bear_keccak.rs
uni-stark/src/config.rs
uni-stark/src/prover.rs
uni-stark/src/verifier.rs
uni-stark/tests/fib_air.rs
uni-stark/tests/mul_air.rs

As opposed to initializing `2` identical challengers in all our examples (one for the prover and one for the verifier), it makes more sense to move this functionality into the StarkConfig.
This PR adds a new method to `StarkGenericConfig` which initializes the challenger (similar to how to get the PCS from the config file).
Additionally, to support this we add a field to Stark Config containing the challenger (which must now implement clone) and the prover and verifier code starts by getting a new clone of this challenger in a similar way to how they get a copy of the PCS.
This is pretty similar to a change in #776 so also accomplishes the goal of moving that PR closer to only adding comments.

Initialize Challenger through Stark Config

---

baby-bear/src/baby_bear.rs
dft/Cargo.toml
dft/benches/fft.rs
dft/src/traits.rs
field-testing/src/dft_testing.rs
field/src/array.rs
field/src/extension/binomial_extension.rs
field/src/extension/packed_binomial_extension.rs
field/src/field.rs
goldilocks/src/goldilocks.rs
goldilocks/src/x86_64_avx2/packing.rs
goldilocks/src/x86_64_avx512/packing.rs
koala-bear/src/koala_bear.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/mersenne_31.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx512/packing.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/monty_31.rs
monty-31/src/x86_64_avx2/packing.rs
monty-31/src/x86_64_avx512/packing.rs
util/src/lib.rs

Currently most of our FFT methods (e.g. `Radix2Dit`, `Radix2DitParallel`) naturally work over any two-adic finite field. This however turns out to lead to a rather impressive degradation in performance when handling extension fields.
When given an extension field, these methods lift all the twiddles to the extension field requiring expensive extension field multiplications and, all of our `Packing` code breaks down. (Most extension fields have `Self::Packing = Self`).
There is a simple solution to this however. Because FFT's are linear we can just split all Extension field elements (or more generally vector space elements) into their base field coefficient form and do the FFT on that. This gives almost a `10x` speed up to the speed of these FFT's.
The main downside is that it does require …

Better Extension Field FFT's

---

dft/src/traits.rs

Adding in the interpretation of `lde` methods of working over any coset not just the subgroup.
Improved default for `lde_batch`. This is a better default as several implementations have a custom implementation
of `coset_lde_batch` and often the fact that the shift is `ONE` won't give any performance improvements anyway.

Minor further improvement to comments and default of DFT trait.

---

field/src/field.rs

@SyxtonPrime can you check that this is appropriate? On my side running the algebra dft benchmarks I've seen improvements from 0% on small dimensions to 7%

`reconstitute_from_base`: make chunks parallel

---

fri/src/two_adic_pcs.rs
interpolation/src/lib.rs

Previously the subgroup was being re-computed in each call to `interpolate_coset`. Here we compute it once in bit-reversed order, which also means we don't have to un-bitreverse `low_coset` and `inv_denoms` and we can use a `par_iter` where we previously couldn't.
On OpenVM regex benchmark, this improves `pcs.open` time by 35%.

perf: precompute more data for interpolate_coset in pcs.open

---

field-testing/src/lib.rs
field/src/helpers.rs
field/tests/helpers_test.rs
fri/src/two_adic_pcs.rs
interpolation/src/lib.rs

Was originally an optimization attempt, but it doesn't do much perf-wise. Still seems cleaner to deal with the coset directly.

refactor: precompute coset rather than subgroup for interpolation

---

matrix/src/dense.rs

A slight variant of the approach in #834. Currently the `.transpose()` methods only work for `RowMajorMatrices`. This PR just adds a couple of generic parameters so that the transpose function works with any `DenseMatrix<T, DenseStorage<T>>` but the functionality should be identical.
Additionally we add a `transpose_in_place` method for `DenseMatrix<T, V>` where `V: DenseStorage<T> + BorrowMut<T>`. Currently this added method uses a temporary so I've left a Todo to fix this.

More general matrix Transpose

---

poseidon2-air/Cargo.toml

jemalloc is only used in the example so it shouldn't be a direct dependency, which can lead to some indirect compilation issues.
Specifically: it seems if you compile for a wasm target on a unix machine, the target_family is still unix but jemalloc won't compile.

chore: make jemallocator dev-dependency

---

baby-bear/Cargo.toml
baby-bear/benches/bench_field.rs
baby-bear/benches/extension.rs
field-testing/src/bench_func.rs
field/src/extension/binomial_extension.rs
field/src/extension/packed_binomial_extension.rs
koala-bear/Cargo.toml
koala-bear/benches/extension.rs
monty-31/src/monty_31.rs
monty-31/src/utils.rs

Given #832, I wanted to play around a little with different options to speed up extension field multiplication.
This PR updates the binomial extension field operations to make use of the `dot_product` method from `PrimeCharacteristicRing`. Additionally we implement fast dot product code for Monty31 Fields. (Doing this for Mersenne31/Goldilocks is left as a TODO. I'll make an issue)
Benchmarks are a little jittery, but this improved dot-product is much better for small values of `N`. The timings around `N = 64` confuse me as they seem to fluctuate a lot depending on if the compiler works out how to vectorize everything so different compilers give different results) At any rate, if you are doing a dot product that large, you should be making use of packedfields to speed it up so it's fine …

Speeding Up Extension Field Muls

---

baby-bear/benches/extension.rs
field/src/extension/binomial_extension.rs

Gets a `10%` speed up for inversion for the degree 5 binomial Babybear extension.
Fewer fun math tricks than the degree 4 case, just finding ways to reduce the number of extension field muls.

Perf: Custom code for inverse in quintic field extension.

---

circle/src/pcs.rs
circle/src/prover.rs
circle/src/verifier.rs
commit/src/adapters/extension_mmcs.rs
commit/src/mmcs.rs
fri/src/hiding_pcs.rs
fri/src/prover.rs
fri/src/two_adic_pcs.rs
fri/src/verifier.rs
merkle-tree/src/hiding_mmcs.rs
merkle-tree/src/mmcs.rs

Currently `BatchOpening` is defined both in `fri/two_adic_pcs` and `circle/pcs`. This PR moves it into `commit/src/mmcs` which seems like a more natural place for it.
In addition, we slightly modify `mmcs` to make use of `BatchOpening` in some of its related methods.

Move BatchOpening into MMCS

---

field/src/field.rs
interpolation/src/lib.rs

@SyxtonPrime I saw that we were missing a test where we test an interpolation on 2 polynomials at a time, therefore with a two-element vector corresponding to the two output interpolations.

interpolation: add test for single interpolation with multiple polys

---

field/src/packed.rs

The `PackedFieldExtension` impl for `F::Packing` is useful when setting `Chalenge = F` for debugging, but the extension packing of `F as ExtensionField<F>` doesn't really pack, if I understand the trait correctly it should pack the slice as `F::Packing` does.
(in optimised/production impl this might never be called tho, because one would probably want to check the degree of extension field and fallback to use trait `PackedValue` if the degree is 1, or because setting `Challenge = F` is not sound at all).

Fix `PackedFieldExtension::from_ext_slice` for `F::Packing`

---

dft/src/radix_2_small_batch.rs
field/src/field.rs
field/src/helpers.rs
field/tests/helpers_test.rs
interpolation/src/lib.rs
matrix/src/dense.rs

Some small cleanups in `p3-field`. The goal is to make the slice operations more uniform (serial vs parallel). 
This PR could go further, and would be happy to discuss.
- make use of the slice functions in other places to benefit of packing 
- move them to `PackedField` (similar to `linear_combination`)
- `scale_vec` -> remove in favor of `scale_slice_in_place` (in p3-interpolation)
- `scale_slice_in_place_single_core` -> `scale_slice_in_place`, make arguments uniform
- `scale_slice_in_place` -> `par_scale_slice_in_place`
- `add_scaled_slice_in_place` -> use packing
- `par_add_scaled_slice_in_place` -> completeness
- `par_add_scaled_slice_in_place` -> added for completeness
- p3-matrix: don't parallelize row scaling
- field.rs: remove unnecessary `#[must_use]`

p3-field: more packing and cleanup

---

.github/workflows/ci.yml

We were caching before installing `cargo-sort`, and somehow (I actually don't fully understand the how) when a CI action was run multiple times in a PR, it would fail when it tried to install `cargo-sort` twice.

Moved CI caching after `cargo-sort` install

---

examples/src/proofs.rs
fri/src/prover.rs
fri/src/two_adic_pcs.rs
fri/src/verifier.rs
interpolation/src/lib.rs

In several places, our prover has the constraint: `EF: ExtensionField<F> + TwoAdicField `
But this is unnecessary. In all cases we can just remove the `TwoAdicField` with either no changes or by making use of the fact that `F` is a `TwoAdicField`.
While it's true that these extension fields are `TwoAdic` we don't need to enforce/use this.

Remove some unnecessary TwoAdicField constraints

---

bn254/src/bn254.rs
bn254/src/helpers.rs
bn254/src/poseidon2.rs

There is a faster method of Montgomery Multiplication/Reduction for Big-ints called Interleaved Montgomery Multiplication.
This PR implements it for the Bn254 field. It gives about a 10% speed up right now.
I've added a pretty long comment in `bn254/src/helpers.rs` describing both how it works and what it assumes on its inputs.

Interleaved Montgomery Multiplication

---

bn254/benches/bench_field.rs
bn254/src/bn254.rs
bn254/src/helpers.rs
field-testing/src/bench_func.rs

Wrote this when working on the improved inversions. It turned out not to be necessary for that but it's worth adding here anyway as it's somewhat hilariously faster than the naive inbuilt one (About1000 times...).

Custom halve impl for Bn254

---

baby-bear/src/baby_bear.rs
koala-bear/src/koala_bear.rs
mersenne-31/src/mersenne_31.rs
monty-31/src/data_traits.rs
monty-31/src/monty_31.rs
monty-31/src/utils.rs
util/src/lib.rs

Following #920 I was wondering if a similar approach could speed up inversions for our 31 bit fields. Turns out the answer is yes!
The following gcd based inversion algorithm gives over a `2x` speed up for inversions of MontyField31's and Mersenne31 (along with their extensions):
|Field | Old Inv Speed (ns) | New Inv Speed (ns) |
| --- | --- | --- |
| BabyBear | 346 | 131 |
| KoalaBear | 343 | 128 |
| Mersenne31 | 183 | 91|
| BabyBear Deg 4 Ext | 475 | 167 |
| BabyBear Deg 5 Ext | 673 | 379 |
| KoalaBear Deg 4 Ext | 477 | 163 |
| Mersenne31 Deg 4 Ext | 322 | 177 |
| Mersenne31 Deg 6 Ext | 432 | 291 |

GCD based inversion for 31 bit fields

---

mersenne-31/src/x86_64_avx512/packing.rs
monty-31/src/x86_64_avx512/packing.rs

To quote clippy: #[must_use]` has no effect when applied to a provided trait method

AVX512 Clippy Complaints

---

bn254/Cargo.toml
bn254/src/helpers.rs
goldilocks/src/goldilocks.rs
util/src/lib.rs

Similar to #920 and #921 we can also speed up inversion in the Goldilocks field but doing a GCD based strategy.
We get about a `2x` speed up with just this PR with an additional `10-20%` once we merge #923.
| Field | Old Inv Speed (ns) | New Inv Speed (ns) | New + #923 Inv Speed (ns) |
| --- | --- | --- | --- |
| Goldilocks | 575 | 283 | 256 |
| Goldilocks Deg 2 Ext | 636 | 318 | 260 |
| Goldilocks Deg 5 Ext | 911 | 605 | 534 |

Fast GCD Inverse for Goldilocks 

---

util/benches/bit_reverse.rs

Previously, the bench_reverse_bits function in bit_reverse.rs calculated the variable n as let bits = 1 << log_size; let n = 1 << bits;. This approach caused n to grow exponentially with increasing log_size, quickly exceeding the representable range of standard integer types and leading to integer overflow or panic for larger values (e.g., log_size = 16 or 24). This was not the intended behavior and made the benchmark unusable for larger bit sizes.
We corrected this by setting n = 1 << log_size;, which properly defines n as the range of numbers that can be represented with log_size bits. This change ensures that the benchmark runs efficiently and safely for all intended values of log_size, and that the random input x is always within the correct range. The variable bits was removed as it …

chore: remove useless bench_reverse_bits benchmark

---

goldilocks/src/x86_64_avx2/packing.rs
goldilocks/src/x86_64_avx512/packing.rs
util/src/transpose.rs

Minor refactors for the AVX2 and AVX512 Goldilocks implementations. Goal is to make the file/implementation more similar to the  `Mersenne31/MontyField31` packed implementations.
Key Changes
- Rename `new` and `get` to `to_vector` and `from_vector`. Add some comments about memory safety.
- Introduce `broadcast` giving a constant version of `From`.
- Add comments and remove some unsafes.
As Goldilocks elements are allowed to be any `u64`, most of the generic `add/sub/mul` and similar functions are not actually unsafe. There are no unchecked invariants that the caller needs to ensure. Hence we can remove many of these unsafe keywords. Similarly `reduce128` will work given any generic `u128` split into `2` `64` bit limbs.

Packed Goldilocks Small Refactor

---

field/Cargo.toml
field/src/interleaves.rs
field/src/lib.rs
field/src/packed.rs
goldilocks/src/x86_64_avx2/packing.rs
goldilocks/src/x86_64_avx512/packing.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx512/packing.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/x86_64_avx2/packing.rs
monty-31/src/x86_64_avx512/packing.rs

Moving the interleave code which is identical between `Mersenne31` and `MontyField31` and mostly similar for `Goldilocks` into a shared crate.
For the most part I've just copied the `Mersenne31/MontyField31` code over. The only exception was with the `AVX2`, `interleave_u64` (Used to be `interleave2`) where the corresponding `Goldilocks` function seems to be faster.
Also added a macro allowing `PackedFieldPow2` to be implemented a little more simply.
Annoyingly, this means we need to add in `nightly-features` to the field crate, but it shouldn't be there for long as we can remove it as soon as Rust 1.89 arrives.

Combining Interleave Code

---

.github/workflows/ci.yml
field/src/op_assign_macros.rs
field/src/packed.rs
goldilocks/src/x86_64_avx2/packing.rs
goldilocks/src/x86_64_avx512/packing.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx512/packing.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/monty_31.rs
monty-31/src/x86_64_avx2/packing.rs
monty-31/src/x86_64_avx512/packing.rs

Currently all 8 of these implementations are totally identical so we add a simple macro to handle them all.
Copied across the `PackedValue` impl to `[T; WIDTH]` which is a little faster and cleaned up the `PackedValue` impl for `T` as well, adding a couple of asserts which should be there. We can't use the macro for these as they have a slightly different structure.

Add a macro for implying PackedValue for PackedFields

---

field/src/extension/binomial_extension.rs
koala-bear/benches/extension.rs

We can do an inverse in an Octic extension by using the norm map to get an element in a quartic extension and using the quartic inverse.
This ends up being a lot faster (About `10x`, from `3000ns` to `300ns`). This time also matches pretty closely to `1` quartic inv and `4` quartic mul's which is exactly what we expect.
Plausibly we could speed this up a little further but it's not really worth the effort as further improvement will likely be pretty marginal.

Fast Octic inverse

---

fri/src/prover.rs
fri/src/two_adic_pcs.rs
fri/src/verifier.rs
fri/tests/fri.rs

Currently the `prove_fri` and `verify_fri` functions accept, as an input, a function `open_input` which either produces (or checks in the case of the verifier) a collection of opening points of our committed matrices at a given index.
These functions are then defined as closures in `fri/src/two_adic_pcs.rs` inside the `open` and `verify` functions. This makes it difficult to follow the logic of those function and of `prove_fri` and `verify_fri` and generally provides some unneeded obfuscation.
This PR replaces both of these closures by functions in `fri/src/prover.rs` and `fri/src/verifier.rs` which should make it easier to follow what's going on. Unfortunately this change completely broke the tests in `fri/tests/fri` as we can no longer pass in a `trivial` `open_input` function. Hence, …

Minor FRI refactor - make open input its own function

---

README.md
baby-bear/Cargo.toml
baby-bear/src/lib.rs
circle/src/pcs.rs
dft/Cargo.toml
examples/Cargo.toml
field/Cargo.toml
field/src/interleaves.rs
field/src/lib.rs
field/src/packed/x86_64_avx.rs
goldilocks/Cargo.toml
goldilocks/src/goldilocks.rs
goldilocks/src/lib.rs
keccak-air/Cargo.toml
keccak/Cargo.toml
keccak/src/lib.rs
koala-bear/Cargo.toml
koala-bear/src/lib.rs
mersenne-31/Cargo.toml
mersenne-31/src/lib.rs
mersenne-31/src/mersenne_31.rs
monty-31/Cargo.toml
monty-31/src/data_traits.rs
monty-31/src/lib.rs
monty-31/src/monty_31.rs
monty-31/src/poseidon2.rs
poseidon2/Cargo.toml
uni-stark/Cargo.toml

As of Rust 1.89.0, `feature(stdarch_x86_avx512)` is now part of the standard feature set and no longer needs to be manually enabled. This means we can completely get rid of our nightly-features flag!
This should make it a little easier to run AVX512 code as you no longer need to use nightly rust (or enable the feature). Due to this I've also deleted the relevant parts from the README.
Annoyingly there are still some bugs in AVX512 on certain systems (#729, #905) so I've added that to known issues now that they can be encountered in standard mode. They should be fixed soon.

Remove Nightly Features

---

bn254/src/bn254.rs
field-testing/src/lib.rs
field/src/array.rs
field/src/extension/binomial_extension.rs
field/src/extension/packed_binomial_extension.rs
field/src/field.rs
goldilocks/src/goldilocks.rs
goldilocks/src/x86_64_avx2/packing.rs
goldilocks/src/x86_64_avx512/packing.rs
mersenne-31/src/aarch64_neon/packing.rs
mersenne-31/src/mersenne_31.rs
mersenne-31/src/x86_64_avx2/packing.rs
mersenne-31/src/x86_64_avx2/poseidon2.rs
mersenne-31/src/x86_64_avx512/packing.rs
mersenne-31/src/x86_64_avx512/poseidon2.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/monty_31.rs
monty-31/src/x86_64_avx2/packing.rs
monty-31/src/x86_64_avx2/utils.rs
monty-31/src/x86_64_avx512/packing.rs
monty-31/src/x86_64_avx512/utils.rs
uni-stark/src/symbolic_expression.rs

Currently `.halve()` is only available for Fields. There is no real reason though why we couldn't also make it available for `PrimeCharacteristicRing`s. Moving this (and `.div_2_exp_u64(a)` which I'll put in a seperate PR) to `PrimeCharacteristicRing` is nice from a consistency standpoint as that is where `.double()` and `.mul_2_exp_u64(a)` are and can also be used to speed up some computations.
(I've checked that this compiles and tests pass on AVX512)
The biggest question here is what should be default implementation of `halve` look like? We have four options:
- Don't give a default and make all rings write what implementation they desire. (Basically all rings should overwrite whatever default we give so we could just force them to).
- Give a default based on multiplying by …

Move halve to ring

---

baby-bear/benches/extension.rs
field-testing/src/bench_func.rs
field/src/extension/binomial_extension.rs
field/src/extension/mod.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/extension.rs
monty-31/src/no_packing/mod.rs
monty-31/src/x86_64_avx2/packing.rs
monty-31/src/x86_64_avx512/packing.rs

Same idea as #988 and #980 but for base x extension multiplication.
It would be nice to do a small refactor letting us use `AVX2` and `AVX512` code at the same time but that will have to be a larger PR. Ideally the AVX512 code here should really just be using the AVX2 code instead of padding by zeroes a lot.
At any rate, we seem to get around a `2-2.5x` speed up to throughput on AVX2 for sizes `4, 5, 8`.
Surprisingly, for AVX512 this gives basically no speed up in the `4` case and only about a `1.5x` speed up in the `8` case. Probably due to the scalar code being vectorized by the compiler more efficiently for some reason? Might be related to the fact that there are too few field elements to really efficiently pack into 512 bit vector, or this could also be an indication that the …

Speed Up Base-Extension Multiplication

---

baby-bear/src/poseidon2.rs
examples/src/airs.rs
koala-bear/src/poseidon2.rs
mersenne-31/src/aarch64_neon/poseidon2.rs
mersenne-31/src/poseidon2.rs
monty-31/src/poseidon2.rs
poseidon2-air/src/air.rs
poseidon2-air/src/generation.rs
poseidon2-air/src/vectorized.rs
poseidon2/src/generic.rs

Now that `halve` and `div_2_exp_u64` are both part of `PrimeCharacteristicRing` we can update `GenericPoseidon2LinearLayers` to make use of this.
Currently, `GenericPoseidon2LinearLayers<R, WIDTH>` takes `2` parameters and implements the external and internal layer matrix multiplication for arrays of the form `[R; WIDTH]`.
This PR drops the `R` parameter, leaving us with `GenericPoseidon2LinearLayers<WIDTH>` and then has this trait implement external and internal layer matrix multiplication for arrays of the form `[R; WIDTH]` for all `R: PrimeCharacteristicRing`. This is much simpler and leads to not having to implement this trait multiple times.
Propagating the change through to the MontyField31's we can simplify the trait `InternalLayerBaseParameters` as we can now implement the same …

Generic Poseidon2 Simplifications

---

koala-bear/src/poseidon2.rs

This is done according to this Python spec https://github.com/leanEthereum/leanSpec/pull/6 where the round constants are produced according to the official paper.
@khovratovich Do we have an official public repo or something like this to link in the doc for the interested reader to be able to generate again the constants by himself?
I've used this Python script to check that the constants here in Rust correspond exactly to what we have in the Python spec:
```python
from typing import List
_RAW_CONSTANTS_16: List[int] = [
2128964168,
288780357,
316938561,
2126233899,
426817493,
1714118888,
1045008582,
1738510837,
889721787,
8866516,
681576474,
419059826,
1596305521,
1583176088,
1584387047,
1529751136,
1863858111,
1072044075,
517831365,
1464274176,
1138001621,
428001039,
245709561, …
```

koalabear: add default poseidon constants

---

field/src/integers.rs
field/src/packed/packed_traits.rs
monty-31/src/monty_31.rs
util/src/lib.rs

First pass at #1014 
Had a look through and fixed the ones I came across. I assume there are many more out there.
We can also replace some debug_asserts as this will not affect run times.
Unfortunately, we cannot use assert_eq so I had to remove those (and any string formatting for error messages)

Compile Time asserts 

---

monty-31/src/aarch64_neon/mod.rs
monty-31/src/aarch64_neon/packing.rs
monty-31/src/aarch64_neon/utils.rs

@SyxtonPrime The approach is really similar to the AVX one so I think this is the way to go but do you have a specific way to benchmark this efficiently to have apple to have comparisons with the other architectures?

monty31: add halve for aarch64 neon

---

examples/src/tests.rs

Very small fix, ran into a bug where `RecursiveDFT` could get initialised with value `0` which breaks `log_2_strict_usize`.
Not really sure what the `>> VECTOR_LEN` is doing there anyway, nothing in that example references keccak so I just removed it and replaced it with the "correct" size.

Fixing RecursiveDFT initlialisation

---

Cargo.toml

Fix workspace configuration inconsistency where the `mds` module was defined in workspace.dependencies but missing from the members list. This ensures the module is properly included in workspace-wide operations like `cargo build`, `cargo test --workspace`, and CI/CD pipelines.
Changes:
- Added `mds` to workspace members list in alphabetical order

Add missing `mds` module to workspace members

---

monty-31/src/x86_64_avx512/poseidon2.rs
monty-31/src/x86_64_avx512/utils.rs

#1069 pointed out that the doc comments in the AVX512 impl are pretty bad (and wrong in places).
Serves me right copy-pasting from the AVX2 impl. The code is all right atleast.

Poseidon2 doc comment fixes

---

README.md
examples/examples/prove_prime_field_31.rs
examples/src/dfts.rs
examples/src/parsers.rs

Pretty self explanatory, adds `Radix2DFTSmallBatch` to the dft options in the examples.
In some cases it's about 10% faster than the current FFT's. (In other cases it is slower, not clear exactly when/why it is faster/slower).
Unfortunately, this required implementing an Enum for the possible return types as `Radix2DFTSmallBatch` returns a `RowMajorMatrix` whereas the other methods return a `BitReversedView<RowMajorMatrix>`.

Add SmallBatchDft to example options.

---

field/src/packed/aarch64_neon.rs

- add typed helpers for converting between [u32; 4] and uint32x4_t
- localize and document the unsafe transmute usage in packed add/sub
- keep SIMD behaviour unchanged while silencing missing annotation lint

fix: Clarify NEON transmute conversions
